### ISSUE TITLE
Refactor code to have a single list of feature classes

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbology#116]
Issue noted by @kgonzago during PR:

https://github.com/Esri/military-symbol-editor-addin-wpf/pull/114#discussion_r91603072 

The list of valid datamodel feature classes is in 2 places:

https://github.com/Esri/military-symbol-editor-addin-wpf/tree/dev/source/ProSymbolEditor/Models/SymbolSetMappings.cs
https://github.com/Esri/military-symbol-editor-addin-wpf/tree/dev/source/ProSymbolEditor/Models/MilitaryOverlayDataModel.cs 

See if the code can be refactored to get the single list of valid feature classes from one location/class

**Comment by topowright** [comment]
@csmoore please refactor in a way that we only have one instance of the schema within the code.

**Comment by csmoore** [comment]
Addressed in PR #258 - Commit: https://github.com/Esri/military-symbol-editor-addin-wpf/pull/258/commits/c166f708b2635b32a1a1d1365752110d916c2bcd

**Comment by kgonzago** [comment]
Based on this [commit](https://github.com/Esri/military-symbology/commit/c166f708b2635b32a1a1d1365752110d916c2bcd), I verified the list of valid data model feature classes is now in one class.
