### ISSUE TITLE
User should be prompted about which schema they intend to add to their project at the outset, not when selecting the first symbol they want to use

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbology#154]
I think that a pop up should appear when you first open the symbol editor, asking which schema you would like to add to the map. This is, of course, after the editor does a check to see if the schema is already in the map or not.

This is the current workflow:
1. Open military symbol editor in a new project with a map 
2. In the search tab, search for a symbol by typing in the search bar.
3. When you see the results populate the text bar, select a symbol. This is when the pop up appears

We need the pop up to appear at the beginning, it just makes more sense. That way, the user can select 2525D or Bc2 and then begin their workflow of searching for symbols, or importing favorites.

**Comment by csmoore** [comment]
I think the only reason we did it the other way (wait until the user had actually used the Symbol Editor before prompting) was in case the Symbol Editor was open (from a previous use) but the user had no intention of using. 

But this workflow seems fine also:

1. On New Project Load
2. Prompt: "The Military Symbol Editor is Active, and no Military Schema is found in the project, would you like to add the Military Schema to your project?"
    1. Yes, 2525D
    2. Yes, 2525B Change 2
    3. No, Close Military Symbol Editor

**Comment by csmoore** [comment]
Addressed in PR #258 

Prompt added on Start when the Military Overlay Addin Dockpane is first used to prompt:

![form-adddatamodel](https://user-images.githubusercontent.com/3090809/44665286-85aa4900-a9e3-11e8-9f49-2e2209c4eb34.PNG)
