### ISSUE TITLE
save pro project after adding military information model

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-symbology#175]
When working with the MSE, the miliary information model is added to your pro project with correct symbology/rendering.  If the Pro project is not saved prior to closing the app that symbology and rendering is lost.  The miliary information model remains within the project gdb but is unuable and another pro project must be created to use the MSE.

To fix: have the project save after adding the military information model.

**Comment by lfunkhouser** [comment]
User is prompted to save project on close. If user selects, "No", the project/symbology will not save as expected. Closing.
