### ISSUE TITLE
Combining the Modify and Symbol tab

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#204]
### Current Behavior
There is overlapping functionality on the two tabs. All the functionality that is on the Modify tab is on the Symbol tab other than the Select button and the Selection List. 

The modify tab has a selection button to pick the symbols you want to edit.
The interaction with making changes to the symbol takes place on the Symbol or Label tabs.

### Expected Results
Combining the selected symbol in a tab inside the Symbol tab where a user would possible select from the list and then be able to tab over to the attributes of the symbol. 

Also moving the select button to the left side of the add-in will not allow the button to disappear when the pane is not extend far enough to the right.

**Comment by csmoore** [comment]
You  could move the selection to a symbol tab, but it would get crowded if you still allowed multiselect, but easier if you could only select one at a time - here are the 2 tabs now:

![image](https://user-images.githubusercontent.com/3090809/34042051-dd71e56a-e168-11e7-9743-c36488bf8e0f.png)

![image](https://user-images.githubusercontent.com/3090809/34042116-236d241c-e169-11e7-8e0a-827aa2f731a3.png)

**Comment by csmoore** [comment]
Address in PR #319  : 

1. Remove the modify tab
2. Move Select Button
3. Change Select to single/point-select 

Should look like this after PR:

![image](https://user-images.githubusercontent.com/3090809/47526433-af5de000-d86d-11e8-836c-edaf6c1a743c.png)

**Comment by dfoll** [comment]
Created build MSE build 23 to test this ... will merge after testing, will rebuild after doc has also been updated   \\...\...\Development\Commercial\Solutions\DefenseSolutions\MilitarySymbolEditor\Testing

**Comment by dfoll** [comment]
This documentation appears on DEV. MT build 122 and MSE build 24 have these changes in the distributed documentation, as well as pulling in PR #319
