### ISSUE TITLE
Unable to change the entity field for an existing symbol

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbology#222]
As noted in #214 - [here](https://github.com/Esri/military-symbol-editor-addin-wpf/issues/214#issuecomment-371943673) 

When using 2525D and  the Symbol Editor, it does not provide a way to change the symbol type (determined by the entity field) - for example change a symbol from "Infantry" to "Artillery" 

Repro Steps:

1. Select an existing symbol on the map using the select tool on the Modify Tab
2. Click Next (or Symbol Tab)
3. You can change the other properties of the symbol, but not the property that changes the symbol entity field/type (this is possible using in 2525B)

Example (2525D)
![image](https://user-images.githubusercontent.com/3090809/38575895-8817b140-3cca-11e8-80cb-15d83f6fe405.png)

Example (2525B)
![image](https://user-images.githubusercontent.com/3090809/38575782-42874708-3cca-11e8-98e8-f84d14bbbf64.png)

**Comment by csmoore** [comment]
This attribute has been added to the Symbol tab for 2525D:

![image](https://user-images.githubusercontent.com/3090809/52722828-6a73cb80-2f7a-11e9-845b-6bd81b702ef8.png)

Just let me know if you prefer it to appear first in the list vs. last in the list (or elsewhere). For now, I picked last in list on the basis it would not normally be changed.

**Comment by csmoore** [comment]
While testing this, I noticed some issues - that I am not sure are related to the changes, but just commenting here in case we see in previous versions:

1. A deadlock issue when quickly selecting, modifying, and saving edits for a symbol
2. Symbol selected was not the top-most visible symbol (when multiple symbol in same location), so when you saved edits the symbol did not appear to change
3. If modifying a line symbol that touched other symbols, this symbol was not re-selected after clicking the Save Edits button (another symbol was selected)

These issues were addressed in commit: https://github.com/Esri/military-symbology/commit/2b5669a7dd1a8f9f43c623b767248bf5725311b0

**Comment by csmoore** [comment]
Build `Solutions\DefenseSolutions\MilitarySymbolEditor\March2019\Dev\54\` created for verification.

**Comment by dfoll** [comment]
Tested `Solutions\DefenseSolutions\MilitarySymbolEditor\March2019\Dev\54\`  confirmed fixed. 2525D and APP-6D now can change entity. Confirmed it functionally behaves as well.

![image](https://user-images.githubusercontent.com/5322669/52876436-0d0f8400-310c-11e9-888c-81f693e3f127.png)

![image](https://user-images.githubusercontent.com/5322669/52876446-14cf2880-310c-11e9-92ef-c99174e30020.png)

**Comment by dfoll** [comment]
the words are written and maps updated, experiencing some navigation issues after publishing so leaving the G-Doc (CMS) label on until those are fixed, or at least understood.

**Comment by BobBooth** [comment]
Verified doc updates on Dev.
