### ISSUE TITLE
BUG-000113850  Military Symbol Editor: Symbol "Foxhole, Emplacement or Weapon Site" (2.X.3.3.4) is not implemented according Mil-Std 2525B Chg 2

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#231]
<div><div>
<span><b>Salesforce ID:</b> BUG-000113850</span><br/>
<span><b>Salesforce Submitter:</b> Vanshika Bharadwaj</span><br/>
<span><b>Salesforce Submit Date:</b> 5/09/2018 3:08 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\<server>\sf_filestore\PRD\Attachments\Defects\BUG-000113850</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS Pro</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 2.0</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Steps to Repro:**

- Install the Military Symbol Editor for ArcGIS Pro. (https://solutions.arcgis.com/defense/help/military-symbol-editor/)
- Search for the Symbol “Foxhole, Emplacement or Weapon Site” using the Symbol ID: G*MPSW----****X.
- Observe that the symbols will appear titled as Fortified which is not defined in the MIL-STD 2525B_CHG-2.PDF (Page number – 469)
- It is possible to define attributes which are not required by the standard (e.g. Echelon [B], Date valid [W], Date expired [W1], Unique Identifier [T], Additional Information [H]). (Pg-469)
- The Symbol is not drawn according to Mil-Std 2525B change 2. Mil-Std 2525B chg 2 requires exactly 2 anchor points. (Page-469)
- For “planned“ / “anticipated” symbols the Line should be dashed : BUG-000111950
- Please find the PDF attached.

**Comment by lfunkhouser** [comment]
To address the issue: 
- [ ] Update the Name of the symbol in the stylx from Protection Lines: Fortified Line to Survivability: Foxhole, Emplacement or Weapon Site
- [ ] Update the tags on the symbol to include: mobility; survivability; foxhole; emplacement; weapon site. The current tags are Control Measure;Protection Lines;Fortified Position;G*MPSW----****X;MAIN;Line;Protection Lines : Fortified Position;25291000

These changes will allow a user to discover the correct mobility/survivability symbol by either typing in the name of the symbol or the SIDC.

This happened in the mapping of MIL-STD-2525D and MIl-STD-2525B Change 2. MIL-STD-2525B Change 2 symbol G*MPSW----****X, Foxhole, Emplacement or Weapon Site is the same graphical representation of the MIL-STD-2525D Fortified Position symbol, Symbol Set: 25; Code: 291000

For the other issues logged in the support issue:
The same schema is currently used for all symbols, so it will be possible for a user to add additional attributes that are not needed, required, or displayed for all symbols. This is currently as designed.

The symbol is drawn according to the MIL-STD-2525B Change 2 standard if only 2 anchor points are used. Users are currently not limited to the required number of points and can sketch the symbol using more than the required number of points. This is currently as designed.

Planned/anticipated status of control measure symbols would require a core level rendering change. We will support this when the underlying technology supports this change.

**Comment by BobBooth** [comment]
The same issue applied to 2525C.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#50
