### ISSUE TITLE
Selection button does not follow dark theme

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#246]
#### Situation

The selection tool on the modify tab has a gray background that should not be present when using the dark theme in ArcGIS Pro. The photo below is the way that the button looks when you arrive on the modify tab for the first time. 

![image](https://user-images.githubusercontent.com/5488313/42328114-8202e7a2-803b-11e8-8c89-920d96288252.png)

#### Best button comparrisson
Using the Raster Funtion Template builder has the best example I can find for how a button in dark theme should looked. 

#### Expected outcome
The the button has the same look and feel as other buttons in ArcGIS Pro. Also, that it uses the ArcGIS Pro dark theme template.

**Comment by csmoore** [comment]
Addressed in PR #251

Addressed by:

1. Changing styling for background/border
2. Removing focus from button (it was the only button so got focus by default) 

After PR should look like:

Button Dark (not pressed/toggled):

![selectnotoggled](https://user-images.githubusercontent.com/3090809/43597508-44143c2c-9650-11e8-84fb-42bca23d7d7e.PNG)

Button Light (not pressed/toggled):

![selectnotoggled-light](https://user-images.githubusercontent.com/3090809/43597512-47674d60-9650-11e8-9414-23ebbb09f12b.PNG)

Button Dark (Tool enabled/toggled - note you should get the background+border color here to indicate that the tool is pressed/toggled):

![selectselectedtoggled](https://user-images.githubusercontent.com/3090809/43597571-72237498-9650-11e8-8466-bad4ea5a6beb.PNG)
