### ISSUE TITLE
Forward and back buttons are not in line with ArcGIS Pro's dark theme

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#247]
#### Situation
The left and right arrows have gray squre backgrounds behind them that should not be present when using the dark theme in ArcGIS Pro.
![image](https://user-images.githubusercontent.com/5488313/42332295-9e10e1f6-8045-11e8-84e2-e5950a16dddd.png)

![image](https://user-images.githubusercontent.com/5488313/42328705-fe04bdd4-803c-11e8-8f87-49acf29c1c77.png)

#### Best button comparrisson
Using the buttons on the edit tab allow an understanding of how the buttons should highlight when a mouse has hovered over them. 

#### Expected outcome
The the buttons have the same look and feel as other buttons in ArcGIS Pro. Also, that it uses the ArcGIS Pro dark theme template.

**Comment by csmoore** [comment]
The addin uses the built-in Pro Button/style "Esri_BackButton" so there may be a problem with this style.

@topowright - can you provide a screenshot or more info on the Edit Tab example (I don't see these buttons on the Pro edit tab ribbon)

All of the examples I see in Pro are the "Esri_BackButtonSmall" which is a different button in the SDK. Example from the Tasks pane:

![image](https://user-images.githubusercontent.com/3090809/42329805-99868d58-803f-11e8-987b-c0829ac201d9.png)

**Comment by dfoll** [comment]
@csmoore  @topowright The example of the arrow on the tasks pane is correct. The initial write up has been updated to clarify it is the squared off background behind the button that is undesirable.

**Comment by csmoore** [comment]
Addressed in PR #250 with a workaround.

This is an issue with the Pro-provided "Esri_ButtonBack" (which probably should be reported to them)  the workaround was just to substitute the working small version("Esri_ButtonBackSmall") and scale it to a larger size.

Before PR:

![image](https://user-images.githubusercontent.com/3090809/43553941-8b305e9c-95bf-11e8-87bb-28e7cbea3686.png)

![image](https://user-images.githubusercontent.com/5488313/42332295-9e10e1f6-8045-11e8-84e2-e5950a16dddd.png)

After PR:

![image](https://user-images.githubusercontent.com/3090809/43553953-9331c28e-95bf-11e8-86bb-34e8c509126c.png)
