### ISSUE TITLE
The About and Setting menu do not follow the dark theme

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#248]
#### Situation
The About and Settings buttons are not the correct color for ArcGIS Pro dark theme
![image](https://user-images.githubusercontent.com/5488313/42329047-dae233e4-803d-11e8-8a85-c8d46be7ceef.png)

#### Best button comparison
Behavior should be the same as the text (name of the tab) on the ribbon. It is a shade of gray and when you hover over it, it becomes a shade of blue. Also, the fonts used for the About and Settings buttons on the MSE pane should match those used on the ribbon.
![image](https://user-images.githubusercontent.com/5322669/42333151-c9f0a8c2-802e-11e8-980d-283fea515a4f.png)

#### Expected outcome
The the buttons have the same look and feel as other buttons in ArcGIS Pro. Also, that it uses the ArcGIS Pro dark theme template.

**Comment by csmoore** [comment]
That text is intended to be hyperlink text (its a button styled as a link):

Looks like Pro styles these in green:

![image](https://user-images.githubusercontent.com/3090809/42331760-3adefef2-8044-11e8-9ba7-32d96f0d2ee7.png)

**Comment by dfoll** [comment]
@csmoore @topowright the initial issue has been edited with a few more details about the desired outcome

**Comment by csmoore** [comment]
Addressed in PR #249 - should look like this after PR - this style does look better than the previous hyperlink style/color:

Dark:
![image](https://user-images.githubusercontent.com/3090809/43534415-4bec9e6a-9585-11e8-9ff6-54e3704425d9.png)

Dark Hover/Select:
![image](https://user-images.githubusercontent.com/3090809/43534598-c09adbdc-9585-11e8-845f-1ad4c451bce4.png)

Light:
![image](https://user-images.githubusercontent.com/3090809/43534499-8097fc18-9585-11e8-9e4d-b3c610a81e4a.png)
