### ISSUE TITLE
Results in the Search tab are not alphabetical 

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#253]
### Current State
![image](https://user-images.githubusercontent.com/5488313/44113732-e6006850-9fbd-11e8-9d47-d7ab14bd43f8.png)

### Expected results
Search list  should return list of symbols alphabetical

**Comment by joebayles** [comment]
Alphabetical, but still grouped together, right? It seems like it's sorted by the SIDC, which is naturally sorted (though control measures are kind of wacky).

**Comment by csmoore** [comment]
Addressed in PR #314

**Comment by dfoll** [comment]
with build 19 search results are alphabetical based on the full name of the symbol
![image](https://user-images.githubusercontent.com/5322669/46833815-8530fc00-cd5e-11e8-9147-ba97e636d870.png)

- [ ] update issues addressed
- [ ] update checklist test

**Comment by dfoll** [comment]
MT build 120 and MSE build 20 and DEV have updated doc

**Comment by dfoll** [comment]
@BobBooth @topowright @lfunkhouser  ready for doc review
