### ISSUE TITLE
Dictionary Label Rule Conversion failing for several label rule names 

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#260]
_From @csmoore on February 13, 2014 21:41_

The Dictionary Label Rule Conversion is failing for several label rule names that contain the strings (“Irregular” / “Circular” / “Rectangular”) and a couple other cases where the Label names and the Symbol names do not match up exactly.

This results in the dictionary having a "-1" entry in the LabelRules column and the labels not being drawn for that symbol in Runtime.

_Copied from original issue: Esri/military-features-data#15_

**Comment by topowright** [comment]
_From @csmoore on February 13, 2014 21:46_

These are the symbols that need to checked to see if they should have labels (currently the "-1" rules means they don't have/won't draw a label) and need to work correctly with the dictionary conversion:

| ID | Name | SymbolID | LabelRules | Style File |
| --- | --- | --- | --- | --- |
| GFFPACAC-- | Airspace Coordination Area Circular F | GFFPACAC--****X | -1 | C2 Military Operations.style |
| GHFPACAC-- | Airspace Coordination Area Circular H | GHFPACAC--****X | -1 | C2 Military Operations.style |
| GNFPACAC-- | Airspace Coordination Area Circular N | GNFPACAC--****X | -1 | C2 Military Operations.style |
| GUFPACAC-- | Airspace Coordination Area Circular U | GUFPACAC--****X | -1 | C2 Military Operations.style |
| GFFPACAI-- | Airspace Coordination Area Irregular F | GFFPACAI--****X | -1 | C2 Military Operations.style |
| GHFPACAI-- | Airspace Coordination Area Irregular H | GHFPACAI--****X | -1 | C2 Military Operations.style |
| GNFPACAI-- | Airspace Coordination Area Irregular N | GNFPACAI--****X | -1 | C2 Military Operations.style |
| GUFPACAI-- | Airspace Coordination Area Irregular U | GUFPACAI--****X | -1 | C2 Military Operations.style |
| GFFPACAR-- | Airspace Coordination Area Rectangular F | GFFPACAR--****X | -1 | C2 Military Operations.style |
| GHFPACAR-- | Airspace Coordination Area Rectangular H | GHFPACAR--****X | -1 | C2 Military Operations.style |
| GNFPACAR-- | Airspace Coordination Area Rectangular N | GNFPACAR--****X | -1 | C2 Military Operations.style |
| GUFPACAR-- | Airspace Coordination Area Rectangular U | GUFPACAR--****X | -1 | C2 Military Operations.style |
| GHFPATB--- | Area Target Bomb H | GHFPATB---****X | -1 | C2 Military Operations.style |
| GNFPATB--- | Area Target Bomb N | GNFPATB---****X | -1 | C2 Military Operations.style |
| GFFPATC--- | Area Target Circular F | GFFPATC---****X | -1 | C2 Military Operations.style |
| GHFPATC--- | Area Target Circular H | GHFPATC---****X | -1 | C2 Military Operations.style |
| GNFPATC--- | Area Target Circular N | GNFPATC---****X | -1 | C2 Military Operations.style |
| GUFPATC--- | Area Target Circular U | GUFPATC---****X | -1 | C2 Military Operations.style |
| GFFPATR--- | Area Target Rectangular F | GFFPATR---****X | -1 | C2 Military Operations.style |
| GHFPATR--- | Area Target Rectangular H | GHFPATR---****X | -1 | C2 Military Operations.style |
| GNFPATR--- | Area Target Rectangular N | GNFPATR---****X | -1 | C2 Military Operations.style |
| GUFPATR--- | Area Target Rectangular U | GUFPATR---****X | -1 | C2 Military Operations.style |
| GFFPAZII-- | Artillery Target Intelligence Zone Irregular F | GFFPAZII--****X | -1 | C2 Military Operations.style |
| GHFPAZII-- | Artillery Target Intelligence Zone Irregular H | GHFPAZII--****X | -1 | C2 Military Operations.style |
| GNFPAZII-- | Artillery Target Intelligence Zone Irregular N | GNFPAZII--****X | -1 | C2 Military Operations.style |
| GUFPAZII-- | Artillery Target Intelligence Zone Irregular U | GUFPAZII--****X | -1 | C2 Military Operations.style |
| GFFPAZIR-- | Artillery Target Intelligence Zone Rectangular F | GFFPAZIR--****X | -1 | C2 Military Operations.style |
| GHFPAZIR-- | Artillery Target Intelligence Zone Rectangular H | GHFPAZIR--****X | -1 | C2 Military Operations.style |
| GNFPAZIR-- | Artillery Target Intelligence Zone Rectangular N | GNFPAZIR--****X | -1 | C2 Military Operations.style |
| GUFPAZIR-- | Artillery Target Intelligence Zone Rectangular U | GUFPAZIR--****X | -1 | C2 Military Operations.style |
| GFFPAZXI-- | Call For Fire Zone Irregular F | GFFPAZXI--****X | -1 | C2 Military Operations.style |
| GHFPAZXI-- | Call For Fire Zone Irregular H | GHFPAZXI--****X | -1 | C2 Military Operations.style |
| GNFPAZXI-- | Call For Fire Zone Irregular N | GNFPAZXI--****X | -1 | C2 Military Operations.style |
| GUFPAZXI-- | Call For Fire Zone Irregular U | GUFPAZXI--****X | -1 | C2 Military Operations.style |
| GFFPAZCI-- | Censor Zone Irregular F | GFFPAZCI--****X | -1 | C2 Military Operations.style |
| GHFPAZCI-- | Censor Zone Irregular H | GHFPAZCI--****X | -1 | C2 Military Operations.style |
| GNFPAZCI-- | Censor Zone Irregular N | GNFPAZCI--****X | -1 | C2 Military Operations.style |
| GUFPAZCI-- | Censor Zone Irregular U | GUFPAZCI--****X | -1 | C2 Military Operations.style |
| GFFPAZFI-- | Critical Friendly Zone Irregular F | GFFPAZFI--****X | -1 | C2 Military Operations.style |
| GHFPAZFI-- | Critical Friendly Zone Irregular H | GHFPAZFI--****X | -1 | C2 Military Operations.style |
| GNFPAZFI-- | Critical Friendly Zone Irregular N | GNFPAZFI--****X | -1 | C2 Military Operations.style |
| GUFPAZFI-- | Critical Friendly Zone Irregular U | GUFPAZFI--****X | -1 | C2 Military Operations.style |
| GFFPACDC-- | Dead Space Area Circular F | GFFPACDC--****X | -1 | C2 Military Operations.style |
| GHFPACDC-- | Dead Space Area Circular H | GHFPACDC--****X | -1 | C2 Military Operations.style |
| GNFPACDC-- | Dead Space Area Circular N | GNFPACDC--****X | -1 | C2 Military Operations.style |
| GUFPACDC-- | Dead Space Area Circular U | GUFPACDC--****X | -1 | C2 Military Operations.style |
| GFFPACDI-- | Dead Space Area Irregular F | GFFPACDI--****X | -1 | C2 Military Operations.style |
| GHFPACDI-- | Dead Space Area Irregular H | GHFPACDI--****X | -1 | C2 Military Operations.style |
| GNFPACDI-- | Dead Space Area Irregular N | GNFPACDI--****X | -1 | C2 Military Operations.style |
| GUFPACDI-- | Dead Space Area Irregular U | GUFPACDI--****X | -1 | C2 Military Operations.style |
| GFFPACDR-- | Dead Space Area Rectangular F | GFFPACDR--****X | -1 | C2 Military Operations.style |
| GHFPACDR-- | Dead Space Area Rectangular H | GHFPACDR--****X | -1 | C2 Military Operations.style |
| GNFPACDR-- | Dead Space Area Rectangular N | GNFPACDR--****X | -1 | C2 Military Operations.style |
| GUFPACDR-- | Dead Space Area Rectangular U | GUFPACDR--****X | -1 | C2 Military Operations.style |
| GFGPSAE--- | Encirclement F | GFGPSAE---****X | -1 | C2 Military Operations.style |
| GHGPSAE--- | Encirclement H | GHGPSAE---****X | -1 | C2 Military Operations.style |
| GNGPSAE--- | Encirclement N | GNGPSAE---****X | -1 | C2 Military Operations.style |
| GUGPSAE--- | Encirclement U | GUGPSAE---****X | -1 | C2 Military Operations.style |
| GFGPDAE--- | Engagement Area Defense F | GFGPDAE---****X | -1 | C2 Military Operations.style |
| GHGPDAE--- | Engagement Area Defense H | GHGPDAE---****X | -1 | C2 Military Operations.style |
| GNGPDAE--- | Engagement Area Defense N | GNGPDAE---****X | -1 | C2 Military Operations.style |
| GUGPDAE--- | Engagement Area Defense U | GUGPDAE---****X | -1 | C2 Military Operations.style |
| GFFPACSC-- | Fire Support Area Circular F | GFFPACSC--****X | -1 | C2 Military Operations.style |
| GHFPACSC-- | Fire Support Area Circular H | GHFPACSC--****X | -1 | C2 Military Operations.style |
| GNFPACSC-- | Fire Support Area Circular N | GNFPACSC--****X | -1 | C2 Military Operations.style |
| GUFPACSC-- | Fire Support Area Circular U | GUFPACSC--****X | -1 | C2 Military Operations.style |
| GFFPACSI-- | Fire Support Area Irregular F | GFFPACSI--****X | -1 | C2 Military Operations.style |
| GHFPACSI-- | Fire Support Area Irregular H | GHFPACSI--****X | -1 | C2 Military Operations.style |
| GNFPACSI-- | Fire Support Area Irregular N | GNFPACSI--****X | -1 | C2 Military Operations.style |
| GUFPACSI-- | Fire Support Area Irregular U | GUFPACSI--****X | -1 | C2 Military Operations.style |
| GFFPACSR-- | Fire Support Area Rectangular F | GFFPACSR--****X | -1 | C2 Military Operations.style |
| GHFPACSR-- | Fire Support Area Rectangular H | GHFPACSR--****X | -1 | C2 Military Operations.style |
| GNFPACSR-- | Fire Support Area Rectangular N | GNFPACSR--****X | -1 | C2 Military Operations.style |
| GUFPACSR-- | Fire Support Area Rectangular U | GUFPACSR--****X | -1 | C2 Military Operations.style |
| GFGPGAF--- | Fortified Area F | GFGPGAF---****X | -1 | C2 Military Operations.style |
| GHGPGAF--- | Fortified Area H | GHGPGAF---****X | -1 | C2 Military Operations.style |
| GNGPGAF--- | Fortified Area N | GNGPGAF---****X | -1 | C2 Military Operations.style |
| GUGPGAF--- | Fortified Area U | GUGPGAF---****X | -1 | C2 Military Operations.style |
| GFGPAAF--- | Forward Area Air Defense Engagement Zone F | GFGPAAF---****X | -1 | C2 Military Operations.style |
| GHGPAAF--- | Forward Area Air Defense Engagement Zone H | GHGPAAF---****X | -1 | C2 Military Operations.style |
| GNGPAAF--- | Forward Area Air Defense Engagement Zone N | GNGPAAF---****X | -1 | C2 Military Operations.style |
| GUGPAAF--- | Forward Area Air Defense Engagement Zone U | GUGPAAF---****X | -1 | C2 Military Operations.style |
| GFFPACFC-- | Free Fire Area Circular F | GFFPACFC--****X | -1 | C2 Military Operations.style |
| GHFPACFC-- | Free Fire Area Circular H | GHFPACFC--****X | -1 | C2 Military Operations.style |
| GNFPACFC-- | Free Fire Area Circular N | GNFPACFC--****X | -1 | C2 Military Operations.style |
| GUFPACFC-- | Free Fire Area Circular U | GUFPACFC--****X | -1 | C2 Military Operations.style |
| GFFPACFI-- | Free Fire Area Irregular F | GFFPACFI--****X | -1 | C2 Military Operations.style |
| GHFPACFI-- | Free Fire Area Irregular H | GHFPACFI--****X | -1 | C2 Military Operations.style |
| GNFPACFI-- | Free Fire Area Irregular N | GNFPACFI--****X | -1 | C2 Military Operations.style |
| GUFPACFI-- | Free Fire Area Irregular U | GUFPACFI--****X | -1 | C2 Military Operations.style |
| GFFPACFR-- | Free Fire Area Rectangular F | GFFPACFR--****X | -1 | C2 Military Operations.style |
| GHFPACFR-- | Free Fire Area Rectangular H | GHFPACFR--****X | -1 | C2 Military Operations.style |
| GNFPACFR-- | Free Fire Area Rectangular N | GNFPACFR--****X | -1 | C2 Military Operations.style |
| GUFPACFR-- | Free Fire Area Rectangular U | GUFPACFR--****X | -1 | C2 Military Operations.style |
| GFFPAKBC-- | Kill Box Blue Circular F | GFFPAKBC--****X | -1 | C2 Military Operations.style |
| GHFPAKBC-- | Kill Box Blue Circular H | GHFPAKBC--****X | -1 | C2 Military Operations.style |
| GNFPAKBC-- | Kill Box Blue Circular N | GNFPAKBC--****X | -1 | C2 Military Operations.style |
| GUFPAKBC-- | Kill Box Blue Circular U | GUFPAKBC--****X | -1 | C2 Military Operations.style |
| GFFPAKBI-- | Kill Box Blue Irregular F | GFFPAKBI--****X | -1 | C2 Military Operations.style |
| GHFPAKBI-- | Kill Box Blue Irregular H | GHFPAKBI--****X | -1 | C2 Military Operations.style |
| GNFPAKBI-- | Kill Box Blue Irregular N | GNFPAKBI--****X | -1 | C2 Military Operations.style |
| GUFPAKBI-- | Kill Box Blue Irregular U | GUFPAKBI--****X | -1 | C2 Military Operations.style |
| GFFPAKBR-- | Kill Box Blue Rectangular F | GFFPAKBR--****X | -1 | C2 Military Operations.style |
| GHFPAKBR-- | Kill Box Blue Rectangular H | GHFPAKBR--****X | -1 | C2 Military Operations.style |
| GNFPAKBR-- | Kill Box Blue Rectangular N | GNFPAKBR--****X | -1 | C2 Military Operations.style |
| GUFPAKBR-- | Kill Box Blue Rectangular U | GUFPAKBR--****X | -1 | C2 Military Operations.style |
| GFFPAKPC-- | Kill Box Purple Circular F | GFFPAKPC--****X | -1 | C2 Military Operations.style |
| GHFPAKPC-- | Kill Box Purple Circular H | GHFPAKPC--****X | -1 | C2 Military Operations.style |
| GNFPAKPC-- | Kill Box Purple Circular N | GNFPAKPC--****X | -1 | C2 Military Operations.style |
| GUFPAKPC-- | Kill Box Purple Circular U | GUFPAKPC--****X | -1 | C2 Military Operations.style |
| GFFPAKPI-- | Kill Box Purple Irregular F | GFFPAKPI--****X | -1 | C2 Military Operations.style |
| GHFPAKPI-- | Kill Box Purple Irregular H | GHFPAKPI--****X | -1 | C2 Military Operations.style |
| GNFPAKPI-- | Kill Box Purple Irregular N | GNFPAKPI--****X | -1 | C2 Military Operations.style |
| GUFPAKPI-- | Kill Box Purple Irregular U | GUFPAKPI--****X | -1 | C2 Military Operations.style |
| GFFPAKPR-- | Kill Box Purple Rectangular F | GFFPAKPR--****X | -1 | C2 Military Operations.style |
| GHFPAKPR-- | Kill Box Purple Rectangular H | GHFPAKPR--****X | -1 | C2 Military Operations.style |
| GNFPAKPR-- | Kill Box Purple Rectangular N | GNFPAKPR--****X | -1 | C2 Military Operations.style |
| GUFPAKPR-- | Kill Box Purple Rectangular U | GUFPAKPR--****X | -1 | C2 Military Operations.style |
| GFMPOFA--- | Minefields Mined Area | GFMPOFA---****X | -1 | C2 Military Operations.style |
| GHGPSAN--- | Named Area of Interest H | GHGPSAN---****X | -1 | C2 Military Operations.style |
| GFFPACNC-- | No-Fire Area Circular F | GFFPACNC--****X | -1 | C2 Military Operations.style |
| GHFPACNC-- | No-Fire Area Circular H | GHFPACNC--****X | -1 | C2 Military Operations.style |
| GNFPACNC-- | No-Fire Area Circular N | GNFPACNC--****X | -1 | C2 Military Operations.style |
| GUFPACNC-- | No-Fire Area Circular U | GUFPACNC--****X | -1 | C2 Military Operations.style |
| GFFPACNI-- | No-Fire Area Irregular F | GFFPACNI--****X | -1 | C2 Military Operations.style |
| GHFPACNI-- | No-Fire Area Irregular H | GHFPACNI--****X | -1 | C2 Military Operations.style |
| GNFPACNI-- | No-Fire Area Irregular N | GNFPACNI--****X | -1 | C2 Military Operations.style |
| GUFPACNI-- | No-Fire Area Irregular U | GUFPACNI--****X | -1 | C2 Military Operations.style |
| GFFPACNR-- | No-Fire Area Rectangular F | GFFPACNR--****X | -1 | C2 Military Operations.style |
| GHFPACNR-- | No-Fire Area Rectangular H | GHFPACNR--****X | -1 | C2 Military Operations.style |
| GNFPACNR-- | No-Fire Area Rectangular N | GNFPACNR--****X | -1 | C2 Military Operations.style |
| GUFPACNR-- | No-Fire Area Rectangular U | GUFPACNR--****X | -1 | C2 Military Operations.style |
| WO-DHPMO-- | Offshore Loading Facility Area | WO-DHPMO----A-- | -1 | Military METOC.style |
| GFGPOAP--- | Penetration Box F | GFGPOAP---****X | -1 | C2 Military Operations.style |
| GHGPOAP--- | Penetration Box H | GHGPOAP---****X | -1 | C2 Military Operations.style |
| GNGPOAP--- | Penetration Box N | GNGPOAP---****X | -1 | C2 Military Operations.style |
| GUGPOAP--- | Penetration Box U | GUGPOAP---****X | -1 | C2 Military Operations.style |
| GFFPACPC-- | Position Area For Artillery Circular F | GFFPACPC--****X | -1 | C2 Military Operations.style |
| GHFPACPC-- | Position Area For Artillery Circular H | GHFPACPC--****X | -1 | C2 Military Operations.style |
| GNFPACPC-- | Position Area For Artillery Circular N | GNFPACPC--****X | -1 | C2 Military Operations.style |
| GUFPACPC-- | Position Area For Artillery Circular U | GUFPACPC--****X | -1 | C2 Military Operations.style |
| GFFPACPR-- | Position Area For Artillery Rectangular F | GFFPACPR--****X | -1 | C2 Military Operations.style |
| GHFPACPR-- | Position Area For Artillery Rectangular H | GHFPACPR--****X | -1 | C2 Military Operations.style |
| GNFPACPR-- | Position Area For Artillery Rectangular N | GNFPACPR--****X | -1 | C2 Military Operations.style |
| GUFPACPR-- | Position Area For Artillery Rectangular U | GUFPACPR--****X | -1 | C2 Military Operations.style |
| GFFPACRC-- | Restrictive Fire Area Circular F | GFFPACRC--****X | -1 | C2 Military Operations.style |
| GHFPACRC-- | Restrictive Fire Area Circular H | GHFPACRC--****X | -1 | C2 Military Operations.style |
| GNFPACRC-- | Restrictive Fire Area Circular N | GNFPACRC--****X | -1 | C2 Military Operations.style |
| GUFPACRC-- | Restrictive Fire Area Circular U | GUFPACRC--****X | -1 | C2 Military Operations.style |
| GFFPACRI-- | Restrictive Fire Area Irregular F | GFFPACRI--****X | -1 | C2 Military Operations.style |
| GHFPACRI-- | Restrictive Fire Area Irregular H | GHFPACRI--****X | -1 | C2 Military Operations.style |
| GNFPACRI-- | Restrictive Fire Area Irregular N | GNFPACRI--****X | -1 | C2 Military Operations.style |
| GUFPACRI-- | Restrictive Fire Area Irregular U | GUFPACRI--****X | -1 | C2 Military Operations.style |
| GFFPACRR-- | Restrictive Fire Area Rectangular F | GFFPACRR--****X | -1 | C2 Military Operations.style |
| GHFPACRR-- | Restrictive Fire Area Rectangular H | GHFPACRR--****X | -1 | C2 Military Operations.style |
| GNFPACRR-- | Restrictive Fire Area Rectangular N | GNFPACRR--****X | -1 | C2 Military Operations.style |
| GUFPACRR-- | Restrictive Fire Area Rectangular U | GUFPACRR--****X | -1 | C2 Military Operations.style |
| GFFPACEC-- | Sensor Zone Circular F | GFFPACEC--****X | -1 | C2 Military Operations.style |
| GHFPACEC-- | Sensor Zone Circular H | GHFPACEC--****X | -1 | C2 Military Operations.style |
| GNFPACEC-- | Sensor Zone Circular N | GNFPACEC--****X | -1 | C2 Military Operations.style |
| GUFPACEC-- | Sensor Zone Circular U | GUFPACEC--****X | -1 | C2 Military Operations.style |
| GFFPACEI-- | Sensor Zone Irregular F | GFFPACEI--****X | -1 | C2 Military Operations.style |
| GHFPACEI-- | Sensor Zone Irregular H | GHFPACEI--****X | -1 | C2 Military Operations.style |
| GNFPACEI-- | Sensor Zone Irregular N | GNFPACEI--****X | -1 | C2 Military Operations.style |
| GUFPACEI-- | Sensor Zone Irregular U | GUFPACEI--****X | -1 | C2 Military Operations.style |
| GFFPACER-- | Sensor Zone Rectangular F | GFFPACER--****X | -1 | C2 Military Operations.style |
| GHFPACER-- | Sensor Zone Rectangular H | GHFPACER--****X | -1 | C2 Military Operations.style |
| GNFPACER-- | Sensor Zone Rectangular N | GNFPACER--****X | -1 | C2 Military Operations.style |
| GUFPACER-- | Sensor Zone Rectangular U | GUFPACER--****X | -1 | C2 Military Operations.style |
| GFGPAAF--- | Short-range Air Defense Engagement Zone F | GFGPAAF---****X | -1 | C2 Military Operations.style |
| GHGPAAF--- | Short-range Air Defense Engagement Zone H | GHGPAAF---****X | -1 | C2 Military Operations.style |
| GNGPAAF--- | Short-range Air Defense Engagement Zone N | GNGPAAF---****X | -1 | C2 Military Operations.style |
| GUGPAAF--- | Short-range Air Defense Engagement Zone U | GUGPAAF---****X | -1 | C2 Military Operations.style |
| GFFPACBC-- | Target Build-up Area Circular F | GFFPACBC--****X | -1 | C2 Military Operations.style |
| GHFPACBC-- | Target Build-up Area Circular H | GHFPACBC--****X | -1 | C2 Military Operations.style |
| GNFPACBC-- | Target Build-up Area Circular N | GNFPACBC--****X | -1 | C2 Military Operations.style |
| GUFPACBC-- | Target Build-up Area Circular U | GUFPACBC--****X | -1 | C2 Military Operations.style |
| GFFPACBI-- | Target Build-up Area Irregular F | GFFPACBI--****X | -1 | C2 Military Operations.style |
| GHFPACBI-- | Target Build-up Area Irregular H | GHFPACBI--****X | -1 | C2 Military Operations.style |
| GNFPACBI-- | Target Build-up Area Irregular N | GNFPACBI--****X | -1 | C2 Military Operations.style |
| GUFPACBI-- | Target Build-up Area Irregular U | GUFPACBI--****X | -1 | C2 Military Operations.style |
| GFFPACBR-- | Target Build-up Area Rectangular F | GFFPACBR--****X | -1 | C2 Military Operations.style |
| GHFPACBR-- | Target Build-up Area Rectangular H | GHFPACBR--****X | -1 | C2 Military Operations.style |
| GNFPACBR-- | Target Build-up Area Rectangular N | GNFPACBR--****X | -1 | C2 Military Operations.style |
| GUFPACBR-- | Target Build-up Area Rectangular U | GUFPACBR--****X | -1 | C2 Military Operations.style |
| GFFPACVC-- | Target Value Area Circular F | GFFPACVC--****X | -1 | C2 Military Operations.style |
| GHFPACVC-- | Target Value Area Circular H | GHFPACVC--****X | -1 | C2 Military Operations.style |
| GNFPACVC-- | Target Value Area Circular N | GNFPACVC--****X | -1 | C2 Military Operations.style |
| GUFPACVC-- | Target Value Area Circular U | GUFPACVC--****X | -1 | C2 Military Operations.style |
| GFFPACVI-- | Target Value Area Irregular F | GFFPACVI--****X | -1 | C2 Military Operations.style |
| GHFPACVI-- | Target Value Area Irregular H | GHFPACVI--****X | -1 | C2 Military Operations.style |
| GNFPACVI-- | Target Value Area Irregular N | GNFPACVI--****X | -1 | C2 Military Operations.style |
| GUFPACVI-- | Target Value Area Irregular U | GUFPACVI--****X | -1 | C2 Military Operations.style |
| GFFPACVR-- | Target Value Area Rectangular F | GFFPACVR--****X | -1 | C2 Military Operations.style |
| GHFPACVR-- | Target Value Area Rectangular H | GHFPACVR--****X | -1 | C2 Military Operations.style |
| GNFPACVR-- | Target Value Area Rectangular N | GNFPACVR--****X | -1 | C2 Military Operations.style |
| GUFPACVR-- | Target Value Area Rectangular U | GUFPACVR--****X | -1 | C2 Military Operations.style |
| GHGPSAT--- | Targeted Area Of Interest H | GHGPSAT---****X | -1 | C2 Military Operations.style |
| GFMPOU---- | Unexploded Ordinance Area (UXO) | GFMPOU----****X | -1 | C2 Military Operations.style |
| GHFPACZI-- | Zone Of Responsibility Irregular H | GHFPACZI--****X | -1 | C2 Military Operations.style |
| GFFPACZC-- | Zone of Responsibility Circular F | GFFPACZC--****X | -1 | C2 Military Operations.style |
| GHFPACZC-- | Zone of Responsibility Circular H | GHFPACZC--****X | -1 | C2 Military Operations.style |
| GNFPACZC-- | Zone of Responsibility Circular N | GNFPACZC--****X | -1 | C2 Military Operations.style |
| GUFPACZC-- | Zone of Responsibility Circular U | GUFPACZC--****X | -1 | C2 Military Operations.style |
| GFFPACZI-- | Zone of Responsibility Irregular F | GFFPACZI--****X | -1 | C2 Military Operations.style |
| GNFPACZI-- | Zone of Responsibility Irregular N | GNFPACZI--****X | -1 | C2 Military Operations.style |
| GUFPACZI-- | Zone of Responsibility Irregular U | GUFPACZI--****X | -1 | C2 Military Operations.style |
| GFFPACZR-- | Zone of Responsibility Rectangular F | GFFPACZR--****X | -1 | C2 Military Operations.style |
| GHFPACZR-- | Zone of Responsibility Rectangular H | GHFPACZR--****X | -1 | C2 Military Operations.style |
| GNFPACZR-- | Zone of Responsibility Rectangular N | GNFPACZR--****X | -1 | C2 Military Operations.style |
| GUFPACZR-- | Zone of Responsibility Rectangular U | GUFPACZR--****X | -1 | C2 Military Operations.style |

**Comment by topowright** [comment]
_From @csmoore on October 8, 2015 20:44_

2525C issue changing milestone to deferred

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#58
