### ISSUE TITLE
Lighthouse symbol is incorrect - missing rays

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#261]
The Lighthouse symbol is missing the 9 lines/rays at the top of the symbol. This is an issue with the symbol in the stylx files.

mil2525c_b2.stylx
MIL-STD-2525B w/CHANGE 2 and MIL-STD-2525C: 
METOC >Oceanic > Hydrography > Aids to Navigation > Lighthouse
WOS-HALH--P----

mil2525d.stylx
MIL-STD-2525D: 
Hydrography > Aids to Navigation > Lighthouse
Symbol Set 46, Code 120409

Current
![image](https://user-images.githubusercontent.com/3800729/44675416-55fc4080-a9e5-11e8-9076-e7447069eb36.png)

Expected
![image](https://user-images.githubusercontent.com/3800729/44675296-f736c700-a9e4-11e8-82b0-cc6416834aa2.png)

Version
ArcGIS Pro 2.2 and Military Tools 3.1

**Comment by joebayles** [comment]
https://github.com/Esri/joint-military-symbology-xml/blob/dev/svg/Appendices/METOC/Oceanographic/46120409.svg

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#59
