### ISSUE TITLE
2525C data has three invalid Symbol IDs

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#262]
_From @csmoore on July 28, 2014 13:20_

These IDs are in the 2525C tags and dictionary but are not valid:

S_SPS-----_****
S_SPNN----_****
S_UPSS----_****

Just listing here as a known issue (since we noticed this when testing 2525D), but this likely won't be fixed

_Copied from original issue: Esri/military-features-data#31_

**Comment by topowright** [comment]
_From @csmoore on October 8, 2015 20:40_

2525C Issue - changing milestone to deferred

**Comment by lfunkhouser** [comment]
Verify the SIDC are invalid SIDC in MIL-STD-2525B w/CHANGE 2 and MIL-STD-2525C
Remove invalid SIDC from mil2525c_b2.stylx

**Comment by BobBooth** [comment]
@lfunkhouser - looked in the latest version (https://github.com/Esri/military-features-data/tree/dev/military-symbology-styles/mil2525c_b2) of the mil2525c_b2.stylx and these invalid SIDCs are not present.

**Comment by lfunkhouser** [comment]
Closing.
