### ISSUE TITLE
Echelon Indicators not showing up on Control Measure Lines/Areas in Pro

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#264]
_From @csmoore on May 12, 2015 20:19_

@BobBooth noticed this while working on a template, just logging the issue here until we decide where to move/address ( @mbriat mentioned we may need to modify/update how we define these labels )

Symbols like Phase Line, Battle Position should have the echelon indicator overlaid on the line

![image](https://cloud.githubusercontent.com/assets/3090809/7597156/998e6c9a-f8bf-11e4-9159-8f062ac40197.png)

_Copied from original issue: Esri/military-features-data#66_

**Comment by topowright** [comment]
_From @BobBooth on May 13, 2015 19:14_

Data Here: https://esri.app.box.com/files/0/f/3538111917/1/f_30056997353

**Comment by topowright** [comment]
_From @jrweakland on May 14, 2015 1:21_

@csmoore - Please add a milestone and labels based on the importance of this issue. @BobBooth - Please continue to add these issues as you encounter them so that we, as a team, can start to address them as they arise.

**Comment by topowright** [comment]
_From @csmoore on October 1, 2015 17:21_

Assigning to @Dbarnes1 - we will only address in this milestone if there is some straightforward way to change the label rules to handle this case, not if it requires renderer-level changes

**Comment by topowright** [comment]
_From @Dbarnes1 on October 28, 2015 15:31_

@csmoore Adding the echelon indicator would require more than just changing the label rules, because these echelon indicators are not text labels, but rather shapes themselves. In addition, properly adding the echelon indicator would require creating a gap in the boundary line of the area where the indicator could properly be displayed.
Reference:
![image](https://cloud.githubusercontent.com/assets/13024357/10793454/36d38798-7d4e-11e5-9a8e-5b826a4d2e6b.png)

As a result I'm moving this issue's milestone to version- after next.

**Comment by topowright** [comment]
_From @joebayles on October 28, 2015 16:12_

:+1: 
However, I'm pretty sure phase lines don't use echelon, @csmoore.

Not to be nitpicky...

**Comment by topowright** [comment]
_From @ottenw on October 28, 2015 17:3_

Our implementation guidance for amplifiers is that when an amplifier appears in a control measure template, then it is considered mandatory for implementation and test.  Within Control Measures Appendix for the "B" amplifier, there are only three instances - Boundary Line (very important), Battle Position, and Strong Point (area).  The second part of our guidance is that an operator should be able to apply any "authorized/legal" amplifier to any control measure symbol of that type.  So since MIL-STD-2525D Table H-II depicts Echelon Indicator being authorized/legal for all Line, Area, and Boundary Line symbols, then a MIL-STD-2525D compliant system/application should be able to render the Echelon Indicator with any Line or Area.
![ms2525d h-ii extract](https://cloud.githubusercontent.com/assets/6909159/10796336/d7564670-7d6b-11e5-951c-3f83e50b1153.JPG)

**Comment by topowright** [comment]
_From @csmoore on October 28, 2015 17:26_

@ottenw - thanks for the clarification - I definitely did not get that interpretation (that every line/area can/should have an echelon indicator) from the standard before now.

@Dbarnes1 - applying Markers to this lines would definitely be (and in Runtime is) a hard case, I was hoping for a simpler label rule (that might even require a python snippet to do the mapping) that might map echelon value to "I, "II" III", "X" "XX", etc. text label. Just something to prototype if you get a chance. Platoon & below (solid dots) can't easily be shown without a marker, but these echelons are rarely used (to my knowledge) with control measures so we can accept that as a known limitation for now.

**Comment by topowright** [comment]
_From @joebayles on October 28, 2015 23:5_

@ottenw, implementation guidance from who? Also, to confirm... what you're saying is the indicator should be _possible_ for all Lines, Areas, and Boundary Lines, but not _expected_ to be used with anything past the three specific instances?

@csmoore, maybe not squads, but definitely platoons. Totally acceptable for now as a known issue, but something that needs to be fixed.

**Comment by topowright** [comment]
_From @ottenw on October 29, 2015 16:36_

@joebayles , Army implementation guidance for over a decade.  The tables in 2525 like table H-II show all amplifiers that are authorized / legal possible for the 6 types of control measures.  We view the presence of specific amplifiers in a control measure template as designating the use of that amplifier with that symbol as mandatory. For example, an Air Corridor shall have a name (unique designator)minimum altitude, maximum altitude, a width, an effective DTG and an expiration DTG.  Because other amplifiers are authorized/legal per table H-II, a user should have the capability to add any other amplifier in that symbol type.  For example, they may add the H amplifier (additional information) and state in that field "Oncall MEDIVAC air corridor"

**Comment by joebayles** [comment]
@jeconley @mbriat this is what I was talking about.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#61
