### ISSUE TITLE
Upside down labels on Military Lines in Pro/Runtime

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#265]
_From @csmoore on May 13, 2015 19:35_

Depending on how you order the points / draw the line (ex. right to left, left to right) - the line labels may be upside down.  Not sure if there is any way to control this behavior with the label rules/classes or if this is a label engine issue.

Occurs in Pro <=1.1/Runtime<=10.2.5

![image](https://cloud.githubusercontent.com/assets/3090809/7619127/acfe4cee-f984-11e4-80d1-444f45f412ea.png)
Example: Manuever Areas : Axis of Advance : Main Attack - SIDC: 10032500001514030000

_Copied from original issue: Esri/military-features-data#70_

**Comment by topowright** [comment]
_From @jrweakland on May 14, 2015 1:13_

@csmoore - Please assign a milestone and labels for this issue based on your opinion of the issue's importance.

**Comment by joebayles** [comment]
@jeconley @mbriat

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#92
