### ISSUE TITLE
Foreshore symbol has polygon geometry, should be line geometry

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#266]
The Foreshore symbol is drawing with polygon geometry, but it should be a line.
Should be:
![image](https://user-images.githubusercontent.com/3801392/44678764-24946c80-aa07-11e8-90a5-e9c9c6bb3c5c.png)
Runtime app draws it as:
![image](https://user-images.githubusercontent.com/3801392/44678807-3c6bf080-aa07-11e8-8160-b9ada117c684.png)

This is an issue with the symbol in the stylx files.
mil2525c_b2.stylx
MIL-STD-2525B w/CHANGE 2 and MIL-STD-2525C:
METOC >Oceanic > Hydrography > Coastal Hydrography >Foreshore
WO-DHCF---L---

![image](https://user-images.githubusercontent.com/3801392/44679303-991bdb00-aa08-11e8-920e-0c2f0aeba6ad.png)

Seems to be resolved in 2525D style in Military Symbol Editor:
![image](https://user-images.githubusercontent.com/3801392/44678918-910f6b80-aa07-11e8-921c-5796b35d7b10.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#62
