### ISSUE TITLE
Using Multipoint Geometry to draw Control Measures with unique draw rules/control points

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#267]
_From @csmoore on August 4, 2015 12:2_

We were considering using a featureclass with a Multipoint geometry type to indicate to the DictionaryRenderer that the 2525D special draw rules/control points should be used (for example, with an arrow/axis symbol there is a special draw rule that last point indicates the arrowhead width).

However, it doesn't seem we can control the order of the points with multipoint geometries, the vertices always seem to get ordered left to right no matter what order you draw them in. 

So we may not be able to use mulipoint (unless there is some way to keep the points from being reordered) and we should come up with an alternate way to communicate to the renderer that we want to use the 2525D draw rules/control points to draw the symbol (for example an attribute "useStandardDrawRules=true").

![multipoint](https://cloud.githubusercontent.com/assets/3090809/9060027/c27c82a4-3a7d-11e5-9dec-5a555daeaae7.png)
Result of using Multipoint to draw Axis symbol

_Copied from original issue: Esri/military-features-data#108_

**Comment by topowright** [comment]
_From @jeconley on September 9, 2015 14:24_

I discussed this with Craig and what he recalled from the last meeting is that there is an ordering issue with multipoint geometry that would need to be looked at by the geometry team.  They would need to look at the issue first and then we could address any remaining drawing issues after that.  I think it would be best to work directly with the geometry team so I will not enter a CR for this issue.

**Comment by topowright** [comment]
_From @csmoore on September 9, 2015 15:8_

Thanks for the update/checking - I wasn't sure if we needed a CR first to get it looked at (but I did forget to add that to the action items for the minutes of that meeting)

@conklinbd (or @jrweakland ) - can you check with Sergey if we are able to use Multipoint geometry type to arbitrarily order points like specified in the standard. Right now it appears that-like polygon- multipoint reorders the points using some winding rule - so is there some other GDB geotype (other than line) than we can use?

**Comment by topowright** [comment]
_From @jrweakland on November 12, 2015 16:32_

assigning back to @csmoore for reassignment since i am not on the military symbology team

**Comment by topowright** [comment]
_From @csmoore on November 12, 2015 17:58_

Just an update, we didn't make it any further on this, last we were told we could submit a CR to try to get multipoint store behavior changed in desktop, but that seemed like perhaps a radical step so our next incremental step in to try to control this with an attribute ("usecontrolpoints") on line features that do keep their ordering.

Changing the milestone since this likely won't be working by Pro 1.2

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#91
