### ISSUE TITLE
Some Control Measure Point Symbols missing all affiliations but "Friendly"

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#268]
_From @Dbarnes1 on August 26, 2015 18:9_

There are a few remaining control measure point symbols that render correctly, but only in black for "Friendly" affiliation. These point symbols (mostly maritime points) will likely have to be recreated if we care about having red, green, yellow versions. It is important to note that none of them have label amplifiers of any kind, which means that they will not be an impediment to fixing control measure labeling. As a result, this is a low priority task and can be accomplished after label fixes are taken care of. 

Below is the list of point symbols that are only rendering in black/"Friendly" affiliation. 

| Fixed | Symbol Name | Entity | Labeling? |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | Command and Control Points : Center of Main Effort | 130400 | N |
| <ul><li>\- [ ] </li></ul> | Command and Control Points: Airfield | 131900 | Y |
| <ul><li>\- [ ] </li></ul> | Airspace Control Points : Air Control Rendezvous | 180500 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Defended Asset | 210300 | Y |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Air Detonation | 210600 | Y |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Launched Torpedo | 211000 | Y |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Acoustic Countermeasures (Decoy) | 211200 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Electronic Countermeasures (ECM) Decoy | 211300 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : BT Bouy Drop | 211600 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Reported Bottom Sub | 211700 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Moving Haven | 211800 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Screen Center | 211900 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Trial Track | 212200 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Electromagnetic - Magnetic Anomaly Detection (MAD) | 212500 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Forward Observer / Spotter Position | 214000 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Vital Area Center | 214100 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Marshall Point | 214400 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Pre-Landfall Waypoint | 214600 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Estimated Position (EP) | 214700 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Shore Control Station | 217000 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Picket Route | 217400 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Clutter-Stationary or Cease Reporting | 217800 | N |
| <ul><li>\- [ ] </li></ul> | Maritime Points : Tentative or Provisional Track | 217900 | N |
| <ul><li>\- [ ] </li></ul> | Fires Areas : Point Targets : Target-Recorded | 240603 | N |

_Copied from original issue: Esri/military-features-data#129_

**Comment by topowright** [comment]
_From @csmoore on March 2, 2016 16:17_

Moving to next milestone.

@Dbarnes1 @abouffard - this will be a bigger issue with the legacy renderer which currently assumes that there are 4 versions of each controlmeasure symbol (like it does with full frame icons) - so these likely will not display at all there and we may need to fix these as part of that effort (or come up with a way of having the legacy table communicate which control measures do and which do not have 4 icon versions - like setting fullframe to True/False for ControlMeasures also)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#63
