### ISSUE TITLE
Issues with the gct offset in APP6-B

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#269]
_From @topowright on March 29, 2018 17:17_

#### Summary of Issue Encountered:
A customer using the APP6-B stylx files that is famialr wtih our stylx files from 2525 has found an issues with  gct_arrow_with_offset" to be within the TAGS Column

##### Brief summary of issue encountered:
The symbols are available within the stylx file. But they are missing the gct_strings that describe how to create this symbol. Normally they expect something like "gct_arrow_with_offset" to be within the TAGS Column. That will give them the information what kind of edit functions they provide, how many points are involved in that symbol and so on.
 
This is an example how it looks like in MIL2525 and what they expect in APP6B.
 
This is the mil2525d.stylx:
 
   ID         "2598"
   CLASS      "4"
   CATEGORY   "Control Measure : Line"
   NAME       "Maneuver Areas : Axis of Advance : Main Attack : Hostile"
   TAGS       "Control Measure;Maneuver Areas;Axis of Advance;Main Attack;gct_arrow_with_offset;G*GPOLAGM-****X;MAIN;Line;Maneuver Areas : Axis of Advance : Main Attack;25151403"
   
It contains the gct_string that give them some information about the object that will be created. 
 
The app6b.stylx does not contains this gct_string:
 
   ID         "5345"
   CLASS      "4"
   CATEGORY   "Offence"
   Name       "Axis of Advance Ground Main Attack H"
   TAGS       "APP-6(B);Annex E;Command And Control And General Manoeuvre; Offence;Axis Of Advance Ground Main Attack;Hostile;GHCPMOLAM-*****"

##### Describe the product and version used:
ArcGIS Runtime 100.2 and ArcGIS Pro 2.1

##### Include the military symbology standard and version/change set (ex. -2525D):

APP6-B

#### Reproduction Steps and/or Where to Obtain Test Data:
View the informaiton in the sylx file as listed above for the symbol above

##### Step-by-step description of how to reproduce the issue and the expected results:

1. 
2. 

##### Additional information or sample data:
Image from the customer: 
![image](https://user-images.githubusercontent.com/5488313/38103119-58f03f20-333a-11e8-96ef-a2927eb9c681.png)

_Copied from original issue: Esri/military-features-data#319_

**Comment by topowright** [comment]
@lfunkhouser

**Comment by topowright** [comment]
_From @BobBooth on April 13, 2018 18:30_

@topowright - what is the actual scope of this change? Does this apply only to attack arrows, all features, or something in between?
What is the list of changes that need to be changed? Just "ct_arrow_with_offset"?  Are there others? Where are they?
@csmoore

**Comment by topowright** [comment]
@csmoore why was the gct_string not included in the APP6-B?

**Comment by topowright** [comment]
_From @csmoore on April 16, 2018 11:27_

@topowright - I did not work on the development of this original style but that style probably preceded those tags/convention

**Comment by topowright** [comment]
_From @BobBooth on April 16, 2018 14:45_

Might be possible to to join to JMSML CSV to get this data?
https://raw.githubusercontent.com/Esri/joint-military-symbology-xml/master/samples/imagefile_name_category_tags/Military-All-Icons.csv

**Comment by topowright** [comment]
_From @NorbertThoden on April 17, 2018 7:45_

Hi!
I am the customer who caused a case "Esri Case #02068526 - [BOS] reading/loading app6b.stylx fails"
While going forward in that case (thanks to Chris Moore https://github.com/Esri/military-features-data/issues/276#issuecomment-368871017) we were recognizing that all the gct_ strings are missing (in opposite to mil2525d.stylx).

To make the initial description https://github.com/Esri/military-features-data/issues/319#issue-309836286 clear:
There is not just one gct_ string missing - **all** of them are missing (about 20)

To construct a military (multi point) symbol using the mouse, it is necessary to know WHO to construct the symbol.
What is the semantic of every single click the user made to build a military (multi point) symbol...

Hope it helps

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#64
