### ISSUE TITLE
Erroneous METOC Symbols

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#270]
This issue is supporting symbols for 2525D
_From @csmoore on October 2, 2015 11:59_

While @Dbarnes1 was testing (creating a [test dataset for METOC points, lines, and areas](https://github.com/Esri/military-features-data/blob/master/data/mil2525d/test_data/projects/METOCall.ppkx) ), he found this set of symbols that should be fixed/improved :

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [X] </li></ul> | 45110505 | Pressure Systems-Pressure Tendency-Steady | Atmospheric Point |
| <ul><li>\- [X] </li></ul> | 46110304 | Ice Systems-Dynamic Processes-Ice Drift (Direction) | Oceanographic Point |
| <ul><li>\- [X] </li></ul> | 46120310 | Hydrography-Ports and Harbors- Fish Wiers (Point) | Oceanographic Point |
| <ul><li>\- [X] </li></ul> | 46120506 | Hydrography-Dangers/Hazards-Kelp/Seaweed (Point) | Oceanographic Point |
| <ul><li>\- [X] </li></ul> | 45110401 | Pressure Systems-Lines-Trough Axis | Atmospheric Line |
| <ul><li>\- [X] </li></ul> | 45110408 | Pressure Systems-Lines-Convergance Line | Atmospheric Line |
| <ul><li>\- [X] </li></ul> | 45180700 | Isopleths-Operator Defined-Freeform | Atmospheric Line |
| <ul><li>\- [X] </li></ul> | 46120512 | Hydrography-Dangers/Hazards-Reef | Oceanographic Line |
| <ul><li>\- [X] </li></ul> | 45162004 | Weather Symbols-Tropical Storm Systems-Tropical Storm Wind Areas and Date/Time Labels | Atmospheric Area |
| <ul><li>\- [X] </li></ul> | 46120507 | Hydrography-Dangers/Hazards-Kelp/Seaweed (Area) | Oceanographic Area |
| <ul><li>\- [X] </li></ul> | 45170200 | Bounded Areas of Weather - Marginal Visual Flight Rule (MVFR), (Area) | Atmospheric Area |

[Link to original comment](https://github.com/Esri/military-features-data/issues/94#issuecomment-132651398)

Open the [attribute table of test dataset linked](https://github.com/Esri/military-features-data/blob/master/data/mil2525d/sample_data/projects/METOCall.ppkx) for a full description of the issue with that symbol.

_Copied from original issue: Esri/military-features-data#146_

**Comment by BobBooth** [comment]
45110202 - seems fixed
110505 - symbol is blue, should be black
110304 - seems correct to me

**Comment by BobBooth** [comment]
@lfunkhouser - Just wanted to verify that Pro 2.1/CIM2.1 is the earliest version that uses the 2525D stylx?
Checking in order to know what version of Pro to use for making edits to the stylx.

**Comment by BobBooth** [comment]
@csmoore - I'm editing the 2525D stylx using Pro 2.0 - that is working fine, but I find that I cannot edit the mil2525d-lines-areas-labels-base-template.stylx using Pro 2.0

**Comment by csmoore** [comment]
@BobBooth - this makes sense - it looks like this style ( [mil2525d-lines-areas-labels-base-template.stylx](https://github.com/Esri/military-features-data/tree/dev/military-symbology-styles/utils-and-source-data/style-source-files) )  was updated (from Pro 1.2) to Pro 2.1 in this [PR 330](https://github.com/Esri/military-features-data/pull/330) (also links to issue [297](https://github.com/Esri/military-features-data/issues/297) in that repo) - if the repo should be targeting Pro 2.0 instead we can probably go back to that commit and upgrade to 2.0 instead). Things could get a bit confusing if app6d targets Pro 2.1 and mil2525d targets 2.0 so we may need a different approach for this file.

**Comment by BobBooth** [comment]
@csmoore - Probably it was just my decision to go with 2.0 that is wrong.  I will upgrade to Pro 2.1 and continue.

**Comment by BobBooth** [comment]
120200 - Bounded Areas : Marginal Visual Flight Rule (MVFR)
![image](https://user-images.githubusercontent.com/3801392/45172644-ed2a7a80-b1d3-11e8-8288-b70eac187ca4.png)

**Comment by topowright** [comment]
Looking at this issue closer we need to move the following two issues into thier own issue to allow this issue to be closed. The two issues that can be put into seperate issue are: 

45110202	Pressure Systems-High Pressure Center-Tropopause High	Atmospheric Point

45171000	Bounded Areas of Weather-Operator Defined-Freeform	Atmospheric Area

**Comment by topowright** [comment]
@BobBooth please create those issues.

**Comment by BobBooth** [comment]
@topowright - I've pulled those two out into these two issues
https://github.com/Esri/military-symbology/issues/294
https://github.com/Esri/military-symbology/issues/295

**Comment by BobBooth** [comment]
To test, get the mil2525d.stylx from the repo and copy to C:\Program Files\ArcGIS\Pro\Resources\Dictionaries\mil2525d
Open the METOCall.ppkx (attached as a zipfile)
[METOCall.zip](https://github.com/Esri/military-symbology/files/2376396/METOCall.zip)
Find the symbol in the appropriate "issues" sub-layer, zoom to it, and verify that it is now drawing correctly.

**Comment by BobBooth** [comment]
@topowright - I think I fixed https://github.com/Esri/military-symbology/issues/295, you can test that one too.

**Comment by topowright** [comment]
This will be moved to no count. Each symbol issue now is being tracked in separate issues.
