### ISSUE TITLE
Military symbology label issues with lines and areas

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#271]
_From @BobBooth on November 13, 2015 17:41_

@Dbarnes1 
Artillery Target Intelligence Zones date/times should label outside zone to the left, like the Call for Fire zones (note, this is also an issue for Call for Fire Irregular, the other two are right).
![image](https://cloud.githubusercontent.com/assets/3801392/11152267/90d2b166-89ff-11e5-85c4-4fe999f3d110.png)
@Dbarnes1 - seems to apply to all of the target acquisition control measures from ATI through Zone of Responsibility, Circular (Symbol Set Code: 25 Code: 241903)

Also: 
Fires Area Series of Targets Unique Designation (T) field label should be on top edge, not center
Fires Area Series of Targets get correct "nickname" label but it is out of place, in the middle, not on the top edge.  
![image](https://cloud.githubusercontent.com/assets/3801392/9996426/ddfe19f0-6054-11e5-9e2c-30850eca719e.png)

Target Designator missing from Nuke target (25-240602) : 
![image](https://cloud.githubusercontent.com/assets/3090809/11229702/3475a558-8d66-11e5-84d9-6e12c46aa1dc.png)

_Copied from original issue: Esri/military-features-data#174_

**Comment by topowright** [comment]
_From @BobBooth on November 13, 2015 18:26_

@Dbarnes1 - consolidated and renamed this issue, per advice from @csmoore

**Comment by topowright** [comment]
_From @joebayles on February 19, 2016 22:37_

@Dbarnes1 
For Boundary Lines (25110100), there should always be two labels, identifying the two units on either side of the boundary. There should also be a single echelon indicator in the middle of the line.
![image](https://cloud.githubusercontent.com/assets/5016557/13191076/1a1871e6-d716-11e5-96df-9d830c070cf9.png)

My understanding is that Unique Designation and Unique Designation 2 should be those attributes. Currently, these labels do show up, but they should render similarly to the example for readability. At a minimum, there should be one on either side of the line. Currently, they render on the same side and run along the line, and there is no echelon indicator.
![image](https://cloud.githubusercontent.com/assets/5016557/13190998/7ff617d0-d715-11e5-80a0-fdb991ee6abc.png)

**Comment by topowright** [comment]
_From @csmoore on February 22, 2016 13:49_

I see this Boundary Line issue also (Pro 1.2, mil2525.1.2 screenshot below). @Dbarnes1 did make a good faith effort to check all the Control Measure symbols and labels (comprehensive [test dataset of this here](https://github.com/Esri/military-features-data/blob/v.next/data/mil2525d/test_data/projects/ControlMeasuresAll.ppkx) ) - but that symbol lacks a clear template that demonstrate the labels/attributes so checking this symbol was likely not possible (can we CR the standard to add this template like most of the other symbols have?).

The Echelon Issue is a known issue here: https://github.com/Esri/military-features-data/issues/66  

![image](https://cloud.githubusercontent.com/assets/3090809/13219776/2afbd468-d940-11e5-99c4-6d1e9a5e0776.png)

**Comment by topowright** [comment]
_From @joebayles on February 22, 2016 14:20_

Agreed the standard is vague - @abouffard can you work with the team to draft a CR requesting clarification?

**Comment by topowright** [comment]
_From @csmoore on February 22, 2016 14:36_

@Dbarnes1 - at some point (during 1.3) we probably need to take another pass at capturing an accurate master list of the labels problems in style. Looking at the test dataset it shows only about 15 symbols (X 4 affiliation) with missing labels and that number may be low (ex. it doesn't include the symbols listed in this issue). Also the test dataset still shows issues that appear to be fixed, ex:

![image](https://cloud.githubusercontent.com/assets/3090809/13221098/965084d2-d947-11e5-88c9-e52d2b82e382.png)

**Comment by topowright** [comment]
_From @Dbarnes1 on February 22, 2016 15:18_

@csmoore thanks for the clarification. I agree that we should update the style to improve accuracy for 1.3

**Comment by topowright** [comment]
_From @ottenw on February 22, 2016 15:57_

IMHO the 2525D pictures of boundary lines is extremely confusing.  We did not have this problem in 2525A/B/C.  From 2525C:
![boundary example](https://cloud.githubusercontent.com/assets/6909159/13223616/a3a22336-d94a-11e5-8af2-1bb59065d649.JPG)

**Comment by topowright** [comment]
_From @abouffard on February 22, 2016 16:46_

@ottenw , let's work together to draft a CP to make the boundary doc in 2525D Change 1 better.

**Comment by topowright** [comment]
_From @csmoore on March 2, 2016 16:8_

Moving to next Milestone - we should probably do a comprehensive label placement check and do a single table/issue for that like we did last summer with the missing labels

**Comment by topowright** [comment]
_From @joebayles on March 3, 2016 2:51_

:+1:

**Comment by topowright** [comment]
_From @Dbarnes1 on May 25, 2016 21:15_

These label issues are persisting with some of the lines/areas for the 2525C implementation. Thanks to @BobBooth for noticing this in our 2525C test dataset. I think that this serves as a reminder that we should do a comprehensive label placement check once our current project ends.

**Comment by joebayles** [comment]
FYI @jeconley @mbriat

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#65
