### ISSUE TITLE
Only show "/" in label expressions when needed

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#272]
_From @csmoore on February 1, 2016 17:57_

A few of the label expressions have forward slashes "/" that result in a strange label when the field is not present (see image below).

@abouffard says these "/" are optional and we can substitute with a space which will address the issue shown in the screenshot. 

![image](https://cloud.githubusercontent.com/assets/3090809/12726012/57caebea-c8e3-11e5-950b-b111e3d45d08.png)

_Copied from original issue: Esri/military-features-data#192_

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#55
