### ISSUE TITLE
Antitank Ditch draw order is reverse of Antitank Wall for orientation of teeth toward ENY

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#273]
The line symbols for Antitank Ditch and Antitank Wall have triangular teeth along them. It was reported/observed that the draw order of Antitank Ditch was opposite that of Antitank Wall, if you want the teeth to point (per standard) at ENY.
The user found this counter-intuitive and reported it as an issue.  
However, complicating matters a bit, the 2525C standard specified different draw orders for the two symbols (p. 553, p 558).
This should probably be taken to the committee for resolution.

![image](https://user-images.githubusercontent.com/3801392/44683432-5c55e100-aa14-11e8-8b58-a7259c9b8538.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#66
