### ISSUE TITLE
BUG-000090614 Modifiers and designators are not applied correctly to some military symbols in the ArcGIS Runtime SDK for Qt C++ API

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#275]
_From @esride-sju on May 4, 2016 13:21_

This Issues is an issue in the symbol dictionary and should be logged here. 

It is already listed:

BUG-000090614 - Modifiers and designators are not applied correctly to some military symbols in the ArcGIS Runtime SDK for Qt C++ API.

****
LDF Update 2/7/2018
Reported on Runtime 10.2.6
data is here: ...\PRD\Attachments\Defects\BUG-000090614

1. Download the attached "ImageProblems2.zip" file. Unzip this folder and open the project in Qt Creator.
2. Download the attached "ms2525c.pdf" file. Open this file.
3. In the "ImageProblems2.cpp" scroll down to line 66. Here I am populating a QString List with military symbols SIC codes. These symbols are listed below along with the section of the military symbols document that describes how they should be drawn:

Chemically Contaminated Area - Page 618
Fire Support Area (Irregular) - Page 651
Obstacles General Zone - Page 548
Area Target Smoke - Page 649
Fire Support Coordination Line - Page 640
Land Mines - Page 254

4. Comment beside each SIC in the code describes the problem the customer has seen with this symbol.
5. Scroll down to lines 101 and 102 in the "ImageProblems2.cpp" file. Observe each message has a "datetimevalid" parameter and "uniquedesignation" parameter.
6. Run the application. Observe the problems described in step 4.

These symbols and modifiers do not represent the only ones that are not drawn correctly. Both the analyst and the customer feel there are numerous other symbols and modifiers that are not drawn correctly given the huge number of possible combinations.

_Copied from original issue: Esri/military-features-data#217_

**Comment by topowright** [comment]
_From @csmoore on January 31, 2018 16:57_

Important note: this issue concerns the planned/dashed frames which was not supported in the app6b renderer

**Comment by topowright** [comment]
_From @lfunkhouser on February 7, 2018 17:21_

@csmoore This issue is related to 2525C not APP6B

**Comment by topowright** [comment]
This issue is being addressed by multiple teams at esri. Moving this issue to the Military Symbology repo

**Comment by lfunkhouser** [comment]
@csmoore Please look at the customer's code and update the original issue with the problems they are encountering. Customer reports that "Comment beside each SIC in the code describes the problem the customer has seen with this symbol." The repro data is in Box.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#90
