### ISSUE TITLE
Dictionary: Semantik of 'key'

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#276]
_From @NorbertThoden on December 14, 2016 12:6_

While working with the Dictionary of V100 i ran into a couple of problems/questions around the result, especially the result.key.

In the first comments i will post these questions, so you can reply to every single question.

All questions are within this document: 
[2016-12-13_SymbologyQuestions.pdf](https://github.com/Esri/military-features-data/files/651656/2016-12-13_SymbologyQuestions.pdf)

**Contraints:**
I retrieve the results of the dictionary using DictionarySymbolStyle::searchSymbol();
As parameter I used an empty SymbolStyleSearchParamter object, to get the complete model.

These results are retrieved using a widget-based executable. 

The used mil2525d.stylx is from the installer of arcgisRuntmeV100, file size: 21468160Bytes

**Key**
The Dictionary returns properties containing
-	Name (String)
-	Tags (StringList)
-	SymbolClass (String)
-	Category (String)
-	Key (String)
The key has most of the time 8 digits: The SymbolSet (2 digits) and the Entity (6 digits).
But sometimes it´s different

_Copied from original issue: Esri/military-features-data#256_

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#68
