### ISSUE TITLE
Edit military symbology in the web

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#278]
_From @adgiles on March 14, 2018 23:0_

#### Summary of Issue Encountered:

As a user I want to be able to edit/create military symbology in the web client side. To do this I would like a simple GUI editor to create my symbol then the option to add it to the map and it persist in a feature layer. 

_Copied from original issue: Esri/military-features-data#304_

**Comment by topowright** [comment]
This is in the product plan for 2019.

**Comment by lfunkhouser** [comment]
The web functionality will not be developed in this repository. Closing.
