### ISSUE TITLE
Using Pro to create Mobile Style Files seems to create incompatible features with SVG Text

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#283]
_From @csmoore on March 30, 2018 20:40_

#### Summary of Issue Encountered:

Using Pro 2.1 to create mobile style files compatible with the ArcGIS Pro and Runtime Dictionary Renderer is creating incompatible styles (the styles do not appear to work with Runtime 100.2/Pro 2.1 DictionaryRenderer).

##### Describe the product and version used:

Pro 2.1 / Runtime 100.2

#### Reproduction Steps and/or Where to Obtain Test Data:

1. Run ArcGIS Pro (tested on Pro 2.1.0)
2. Catalog | Styles | Create New **Mobile** Style
3. Manage Mobile Style
4. New Point Symbol
5. Properties of New Point Symbol
6. Layers | File | Add SVG from File that contains Text: Ex: 
https://github.com/Esri/military-features-data/blob/dev/military-symbology-styles/utils-and-source-data/svg/Appendices/Air/01110000.svg

7. Open Style file in SQlite editor: observe the Content column of the symbol created in Pro contains text entries:
{"type":"CIMTextSymbol", ..."textString":"MIL"}],...}

8. Using styles created with Pro 2.1 in this manner in Runtime 100.2 and Pro 2.1 causes failures with with these style files and any symbols that contain SVG Text.

9. A complete mil2525d style file created using Pro 2.1 is available at:
https://esri.box.com/s/7yrkehwrgevmkahgwjw6o9kubbfrk28x

    1. Query for incompatible features in this stylx with query: `select * from ITEMS where (Content like '%CIMRGBColor%') or (Content like '%curveRings%') or (CONTENT LIKE '%textString%')` 

##### Screenshot(s) of issue (ex: obtained result vs. expected result):

Crash dump from using style with mil2525d dictionary renderer in Pro:

![image](https://user-images.githubusercontent.com/3090809/38152916-0642a980-3438-11e8-8858-d58394cd587a.png)

_Copied from original issue: Esri/military-features-data#324_

**Comment by topowright** [comment]
_From @csmoore on March 30, 2018 20:45_

@dfoll @ACueva @topowright - can you  report this issue to Core? And also see if these can suggest a workaround to use in the short term - thanks

**Comment by topowright** [comment]
_From @ACueva on April 3, 2018 22:45_

@topowright have you contacted core or would you like me to?

**Comment by topowright** [comment]
_From @lfunkhouser on July 6, 2018 16:39_

@ACueva @topowright @dfoll Did anyone talk to core teams on this issue?

**Comment by topowright** [comment]
_From @ACueva on July 6, 2018 16:42_

@lfunkhouser I have not.

**Comment by topowright** [comment]
_From @csmoore on July 6, 2018 21:2_

@ACueva @dfoll @lfunkhouser @topowright - this issue with incompatibility importing SVG text into Mobile Styles still seems at Pro 2.2. 

There are also about 10 SVGs that used to import at Pro 2.1 that now fail at 2.2 so also tracking down what the new SVG incompatibility might be.

**Comment by topowright** [comment]
_From @jeconley on July 6, 2018 21:13_

I believe this is the issue about text in a vector marker not being supported in RT.  Marc-O installed a fix for that this week.  Please try with the latest version of RT.

**Comment by topowright** [comment]
_From @csmoore on July 9, 2018 12:1_

@jeconley thanks for the update - so Text in VectorMarkers should be supported in the **next** versions of Runtime (100.4) and Pro (2.3) dictionary renderer and at that point we can make all of our edits/changes in Pro

(UPDATE) It looks like the Runtime daily builds were turned off on 6/26 so I'll test this when they are running again.

**Comment by topowright** [comment]
_From @csmoore on July 18, 2018 15:51_

Just an update - and I think this was expected, since it looks like Style Text Markers won't be supported in Runtime until the **next** version based on @jeconley 's comments that this fix/change was just installed - but I tested the Style above on the released version of 100.3 and it no longer crashes, but the Text Markers and not displayed either.

So it looks like we will have to wait until there is a Runtime daily build (these seemed to be currently turned off) until we can test this. FYI @lfunkhouser

**Comment by topowright** [comment]
_From @csmoore on July 20, 2018 15:34_

Update: this just seems to be an issue with Runtime (100.3 or earlier) - the style files created on Pro 2.2 with TextMarkers do seem to work on Pro 2.2 with the Dictionary Renderer.

**Comment by BobBooth** [comment]
@csmoore @topowright - we could edit those SVGs to convert the font symbols to paths.

**Comment by csmoore** [comment]
The style creation process has changed - and Pro supports creating "Runtime" styles now - this issue can be closed
