### ISSUE TITLE
Using Pro 2.3, some of the 2525D Source SVGs are failing to import into Pro Styles

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#284]
_From @csmoore on July 16, 2018 18:11_

#### Summary of Issue Encountered:

Starting at Pro 2.2, some of the 2525D Source SVGs are failing to import into Pro Mobile Styles. The failing SVGs seems to have empty Path elements.

#### Brief summary of issue encountered:

After installing Pro 2.2 and attempting to load the following SVGs from: 
https://github.com/Esri/military-features-data/tree/dev/military-symbology-styles/utils-and-source-data/svg 

svg\Appendices\Space\05120400.svg
svg\Appendices\Land\20120201.svg
svg\Appendices\Activities\40131202_0.svg
svg\Appendices\Activities\40131202_1.svg
svg\Appendices\Activities\40131202_2.svg
svg\Appendices\Activities\40131202_3.svg
svg\Appendices\Atmospheric\45162101.svg
svg\Legacy\2525C\S-G-UCDMM-_2.svg
svg\Legacy\2525C\S-G-UUMSEJ_0.svg
svg\Legacy\2525C\S-G-UUMSEJ_1.svg
svg\Legacy\2525C\S-G-UUMSEJ_2.svg
svg\Legacy\2525C\S-G-UUMSEJ_3.svg

A failure is encountered:

![image](https://user-images.githubusercontent.com/3090809/42773081-3897e7d0-88fa-11e8-9659-a8785dd0b74c.png)

#### Describe the product and version used:

Pro 2.2

#### Step-by-step description of how to reproduce the issue and the expected results:

1. Create or use and exiting Pro Mobile Style 
2. Create a new symbol in the style
3. Click on the layer properties for the new symbols and
4. Load a Shape Marker from file using one of the files above, ex: 
https://github.com/Esri/military-features-data/tree/dev/military-symbology-styles/utils-and-source-data/svg/Appendices/Space/05120400.svg

You receive an error:

![image](https://user-images.githubusercontent.com/3090809/42773331-ea758ce6-88fa-11e8-89c1-814226c831c9.png)

#### Additional information or sample data:

If you look at the failing symbols in an SVG Editor you can see that failing elements/artifacts - these are indeed empty/spurious path elements, but it would be best if Pro could just ignore these. Otherwise we should fix the source symbols to remove these paths (Note: the symbol do import fine if you remove these spurious elements).

![image](https://user-images.githubusercontent.com/3090809/42773400-17cdd266-88fb-11e8-80fa-19671fe40ee3.png)

![image](https://user-images.githubusercontent.com/3090809/42773411-1d74d048-88fb-11e8-9c20-4f0d4db24b9c.png)

Just to summarize this requires a fix in either:

1. Pro to ignore these elements -or-
2. The SVGs to remove these unused/bad paths

FYI @ACueva @dfoll @lfunkhouser @topowright 

_Copied from original issue: Esri/military-features-data#334_

**Comment by lfunkhouser** [comment]
@BobBooth Please take a look at what it would take to fix the SVGs (@csmoore option 2 in the previous comment).

**Comment by BobBooth** [comment]
@lfunkhouser - If it is just the SVGs listed  above, it should not be much effort to delete the empty path elements. I see that they show up in the layer lists, and can be deleted from there.

**Comment by topowright** [comment]
This issue was moved to ArcGIS/military-symbology-styles#31
