### ISSUE TITLE
Customer reported 2525C symbol issues

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#285]
_From @lfunkhouser on April 3, 2018 13:29_

Runtime 100.2
2525C

Customer reported issues after updating their tests from Runtime 10.2.6 to 100.2 and saw the following issues with symbols. The number preceding the issue refers to the page number in the 2525C standard. 

Dictionary_adapter::construct_cim_symbol_ FAILED to create_ SymbolX for id= S-G-USS2--_2, Inserted NULL, I am not finding that string in my test cases

91 - missing the little black tip on the rendered symbols

94 - SUAPMFCL-- the bottom of the L blends in with the bottom of the rendered symbol

97 - SUAPMFUL-- same issue as page 94

104 - SUAPMHUL-- same issue as page 94

105 - SUAPMHCL-- same issue as page 94

108 - SUAPWM---- in the pdf there are no symbols next to the missile icon, in the generated symbol there is a "L" on the right side of the missile icon

113 - All symbols, the text inside the oval is very small to the point of not being legible

114 - SUGPUCDMLA** The vertical line does not extend from the bottom to the top

115 - same issue as page 113

116 - SUGPUCDC-- difficult to differentiate the three lines

122 - SFGPUCAAU- no gap between the bottom of the triangle and the bottom of the symbol

122 - SUGPUCAAC- no gap between the bottom of the ski symbol and the edge of the cloverleaf

129 - SUGPUCVUF- and SUGPUCVUR- the unmanned "V" does not appear as thick as in the spec document, it looks thin like air assault

130 - SFGPUCIO-- same as page 122

131 - SUGPUCIC-- same as page 122

132 - SUGPUCECC- same as page 122

133 - SFGPUCECO- same as page 122

134 - SUGPUCEN-- In the spec the text of "CONST" is wider then the rotated "E"

134 - SUGPUCENN- In the spec the anchor symbol is the same width as the rotated "E"
138 - SUGPUCFRMS** In the spec the chevrons are inside the oval, in the rendered symbol they are above the oval

142 - SUGPUCFMTS** the "V" is above the tip of the arrow in the spec, in the rendered symbol it is partway down the arrow
156 - SUGPUUMA-- same as page 129

158 - SNGPUUMSET** the two triangles are not visible inside the rendered symbol

158 - SNGPUUMSEC** the one triangle is not visible inside the rendered symbol

165 - SUGPUUSRS- in the spec the boxes are empty, in the rendered symbol they are filled in.

165 - SUGPUUSRT- difficult to see that there are 2 different horizontal lines

182 - SNGPUSS2-- shows up as an empty green square, no symbol parts loaded inside of it

167 through 
200 - same as page 158 where Corps and Theater neutral symbols do not show up correctly for most of them except for a select few who do show up properly

199 - SUGPUSXOM- The missile icon middle line is missing and on the friend and neutral it runs out of the top of the box

202 through 204 - horizontal lines are lower on the missile symbol in the rendered symbol than in the spec

215 through 
224 - the horizontal lines for heavy/medium/light are lower in the rendered graphic than on the spec in the non self-propelled graphics

255 through 265 - the small black box is not showing up on top of the rendered symbols

266 - SUSPCLCC-- symbol has "CC" in the spec and "CG" in the rendered symbol

282 - SFSPO-----*****  symbol has background when rendered when in the spec it does not

282 - sub surface symbols do not have gap in border on top
282 - SUUPSB----***** no gap between submarine symbol and bottomed symbol

283 through 285 - "A", "M", "G", "B" text not bold enough, very thin

288 through 296 - underwater symbols do not have background in spec, they do when rendered

973 - IUAPSRAI----*** shows up as upside down black question mark with a red X over it
974 - IUAPSRE-----*** , IUAPSRF-----*** same as page 973

_Copied from original issue: Esri/military-features-data#326_

**Comment by topowright** [comment]
_From @csmoore on April 3, 2018 14:42_

About half of these (ex: the ones that mention sub icons being too close or in slightly different positions) seem consistent with the results from when we initially tested 2 years ago: https://github.com/csmoore/mil2525-testing/blob/master/mil2525c/Mil2525C-Test-Results.md

However the ones that report missing/invisible icons seem like different results and perhaps some new issues. Perhaps as a result of the style being upgraded to CIM 2.0 or drawing changes.

**Comment by topowright** [comment]
_From @t-foster on April 19, 2018 12:30_

I was the original issue writer.  One point about your test results is that they only appear to have checked friendly symbols, not neutral, hostile and unknown which have different shapes and sizes which can affect the symbols.

**Comment by topowright** [comment]
_From @lfunkhouser on May 16, 2018 21:15_

Thanks @t-foster. We have updated many of our test cases to include the other affiliations.

**Comment by topowright** [comment]
_From @kerryrobinson on May 30, 2018 18:20_

Bug number: BUG-000114174

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#70
