### ISSUE TITLE
Support by fire is currently a line symbol with the angle arrows as the linear stroke symbol layers; width of support by fire is a point marker symbol layer

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#286]
_From @Dbarnes1 on May 23, 2017 15:29_

Issue originally posted in: c_api/issues/7245#issuecomment-753196 

Currently the Support by Fire symbol draws with the angle arrows as two line strokes, and the line that indicates width as a shape marker. The length of the angle arrows is actually not important to the symbol according to the standard, as @joebayles has already pointed out:
![image](https://cloud.githubusercontent.com/assets/13024357/26361985/761df080-3f91-11e7-8f49-8fca0a4869dc.png)

The proposed solution to this would be to make the two arrow angle lines shape markers, and make the line that indicates with the line stroke. The symbol would be altered and therefore draw perpendicular to the general direction in which the fire would be moving, which is a little counter-intuitive but closer to how the standard dictates this should be implemented.

I don't think we have a fix currently for implementing the precise angle of the arrows at this time. 

_Copied from original issue: Esri/military-features-data#267_

**Comment by topowright** [comment]
_From @Dbarnes1 on May 25, 2017 21:2_

for update 1 of runtime quartz, they are treating this as a Known Issue as it currently doesn't make sense to implement the symbol the way the standard specifies. Issue about the standard and this symbol located here: https://github.com/Esri/joint-military-symbology-xml/issues/337

**Comment by topowright** [comment]
We need to understand if this is an issue with APP6-B based on our new stylex file.

Currently the information we have related to this issue can be found here: 
https://github.com/Esri/military-features-data/wiki/Known-Issues

**Comment by topowright** [comment]
Document if this is supported in 100.2 and ArcGIS Pro 2.1. We need to understand if this is an issue with APP6 - B as well.

**Comment by topowright** [comment]
_From @BobBooth on April 12, 2018 17:27_

APP-6B should probably match what we do with this. The point ordering is not specified in 6B.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/d90877e6-cc87-4401-badc-309d3358c685)
In contrast, 2525C does specify the point order:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/1533fbd8-1355-4ca5-ac76-f7b46b7a417b)
The Point 1 - Point 2 sequence, to define the length of the line, would make sense.

**Comment by topowright** [comment]
@kerryrobinson @mbriat this is the best example that we currently have of a challenging symbol to draw.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#71
