### ISSUE TITLE
ArcGISRuntime V100: How to display polygon symbols where the geometry is defined by one single anchor point?

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#289]
_From @JoergTurla on December 20, 2016 16:20_

The MIL22525D defines some polygon symbols which requires one anchor point (see attachment). The
size of the shape is determined by additional attributes. For example the shape of
"Rectangular Target" symbol(Symbol Set 25, Code 240802) is defined by the target length and
target width in meters. 

![rectangular_1_pt_25_240802](https://cloud.githubusercontent.com/assets/24681300/21357565/e3ecc1a2-c6d5-11e6-901d-716370d81100.png)

Another example is the "Airspace Coordination Area (ACA) Circular" symbol (Symbol Set 25,
Code 240103). The shape size is defined here by the radius of the circle (in meters).

![circular_25_240103](https://cloud.githubusercontent.com/assets/24681300/21357567/e3ef995e-c6d5-11e6-832c-c4e1d395318a.png)

I tried to set the attributes according to MIL2525D ("length" and "width" for the rectangle
symbol and "radius" for the circle) via Esri::ArcGISRuntime::AttributeListModel 
to the graphic object (Esri::ArcGISRuntime::Graphic). With both examples above the
EsriRuntimeQt throws an exception: C++ exception

 Esri_runtimecore::Common::Invalid_argument_exception at memory location 0x00C7C460

The symbols are not visible on the map. Then I checked the symbologyFieldNames of class 
DictionarySymbolStyle and the attributes length, width and radius are not part of this list.

But a "Call For Fire Zone" symbol (25-241202) works without any Problems in descriped manner.  This
Symbol has a rectangle geometry and requires 2 anchor points. The shape size is defined by a width attribute. 

![rectangular_25_241202](https://cloud.githubusercontent.com/assets/24681300/21357566/e3eda02c-c6d5-11e6-8d7f-1369470d13d2.png)

Setting the width here to the AttributeListModel provides the desired result.

![callforfirezone](https://cloud.githubusercontent.com/assets/24681300/21357783/c7ba320c-c6d6-11e6-9e18-5af5e8e62146.png)

Why does setting the width Attribute works in some case and in other it doesn't?
What do I have to do to get the symbols defined by one single anchor point running?

###### Additional information:
The symbologyFieldNames provided by DictionarySymbolStyle are: 

- identity 
- symbolset 
- symbolentity 
- modifier1
- modifier2
- echelon
- mobility
- array
- context
- indicator 
- status 
- operationalcondition
- specialentity
- subtype
- civilian
- sidc

 The textFieldNames are:

- additionalinformation
- additionalinformation2
- combateffectiveness
- commonidentifier
- credibility
- datetimeexpired
- datetimevalid
- distance
- equipmentteard
- owntime
- higherformation
- idmode
- platformtype
- quantity
- reinforced
- reliability
- sigintmobility
- speed
- staffcomment
- targetdesignator
- type
- uniquedesignation
- uniquedesignation2
- x
- y
- z
- z2

_Copied from original issue: Esri/military-features-data#257_

**Comment by topowright** [comment]
_From @NorbertThoden on February 1, 2017 8:46_

I have the same question

**Comment by topowright** [comment]
_From @csmoore on February 1, 2017 13:27_

Sorry I missed this question earlier. Those attributes:

* "radius"
* "length"
* "width"
* "orientation" 

Should be valid field/attribute names (and documented as such). For the particular/odd case where only one width/height is used, I believe a 2 point *line* is expected as the base geometry (PT1 PT2 in the standard illustration-so it has some way to get the other dimension). But if that doesn't work then it may be a bug you need to submit to Runtime.

I just updated the attribute table to include these missing attributes: https://github.com/Esri/military-features-data/tree/dev/data/mil2525d/core_data/gdbs#otherspecial-cases - hope this helps

**Comment by topowright** [comment]
_From @ottenw on February 1, 2017 14:50_

WRT the "Rectangular Target" symbol (set 25, Code 240802), it is different from other rectangular areas by design.  The attributes of the rectangular target are defined in NATO and US doctrine.  A rectangular target is defined not only by the target length and target width in meters, but also by the target "Attitude", as represented in MIL-STD-2525D by amplifier "AN", and the anchor point located in the center.  Target attitude is defined as the directional alignment of the major (length) axis of a target measured from true north.

**Comment by topowright** [comment]
_From @JoergTurla on February 1, 2017 16:36_

I checked the WRT symbol (set 25, Code 240802) again, setting now all 3 attributes (width,length, attitude). The result is the same as before. The symbol is not drawn and I get many error messages on console output window.

**Comment by topowright** [comment]
_From @csmoore on February 2, 2017 16:31_

@JoergTurla You may just want to confirm that you are using a Multipoint (MultipartBuilder) geometry as the 1 or 2 Pt geometry - mentioned in a previous [issue here if you need more info](https://github.com/Esri/military-features-data/issues/254#issuecomment-262997987) - if that doesn't work you will probably need to submit an issue and use the "Irregular" target symbol versions (defined by only map points) as a workaround for now.

@ottenw - thanks for the background/motivation. One drawback to defining a message with both map points (ex. WGS84 coords) and size attributes in meters is that it does create potential errors/dependencies/feedback on a mapping system to convert between the 2 measurement systems (usually 3 because the map itself will often be in some other coordinate system) so may be something the spec tries to minimize if possible. I realize you often don't have any control over this, and are just a consumer of these message formats, but did want to mention this implementation issue.

**Comment by topowright** [comment]
_From @JoergTurla on February 3, 2017 6:45_

Hi Chris,

thanks for your last comment. I changed my implementation to your proposed workaround. Now the 4 verticies of the rectangle defines the geometry of the symbol. By using a PolygonBuilder this works now.

But what about the second expample ("Airspace Coordination Area (ACA) Circular" - symbol set 25, code 240103). The geometry of this symbol is a circle. It would really not be a practical workaround to rasterize a circle and then pass a Pt list to a PolygonBuilder. So what can I do to get this working too.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#89
