### ISSUE TITLE
 Identify the set of differences between APP-6(D) and MIL-STD-2525D

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#290]
_From @csmoore on March 14, 2018 20:28_

### Background

APP-6(D) data products will be created from ones produced for MIL-STD-2525D. These data products include:

1. Mobile style 
2. Schema/GDB 
3. Metadata used to produce Mobile style, GDB  

In order to create these products the team should first produce a short synopsis/document that highlights and identifies the set of differences between APP-6(D) and MIL-STD-2525D.

### Current State

No document of set of differences between APP-6(D) and MIL-STD-2525D exists.

### Steps to Reproduce / Requirement / Workflow

Create document/writeup/report that explains differences between APP-6(D) and MIL-STD-2525D with respect to:

- [ ] Symbols/icons
- [ ] Attributes
- [ ] Labels 

### Expected Results / Behavior

Writeup of set of differences between APP-6(D) and MIL-STD-2525D exists.

### Version

**MIL-STD-2525D 10 JUNE 2014**
http://www.jcs.mil/Portals/36/Documents/Doctrine/Other_Pubs/ms_2525d.pdf

**APP-6D Edition D Version 1 OCTOBER 2017**
http://nso.nato.int/nso/zPublic/ap/PROM/APP-6%20EDD%20V1%20E.pdf

_Copied from original issue: Esri/military-features-data#298_

**Comment by topowright** [comment]
_From @csmoore on March 14, 2018 23:8_

Quick Note: a very quick/high level diff analysis is here: https://github.com/Esri/military-features-data/issues/293#issuecomment-363813115

@joebayles - the APP-6D standard does mention cyberspace in several sections (Ex: A-6, Table A-4: Symbol Set) - are you sure this has been removed?

**Comment by topowright** [comment]
_From @joebayles on March 18, 2018 21:1_

@csmoore it hasn't been removed. I should clarify: MIL-STD-2525D Change 1 has brand-new cyberspace symbology (including it's own frame shape). MIL-STD-2525D and APP-6D have the same cyberspace symbols. I apologize for the confusion.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#72
