### ISSUE TITLE
Military Overlay layer package in MSE

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#293]
@csmoore are we using the same layer file that is being used by Military Overlay in the Military Symbol Editor?

**Comment by csmoore** [comment]
@topowright - the should be the same - they also seem to have a similar date (Q3-Q4, 2017)

https://github.com/Esri/military-symbology/tree/dev/source/ProSymbolEditor/LayerFiles
http://solutions.arcgis.com/defense/help/military-overlay/
