### ISSUE TITLE
METOC 2525D and 2525B Label issue - Position of height value falls on center of symbol, should be above bottom edge

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#294]
This is an issue in:
- [ ]  2525D
- [ ]  2525C
- [ ]  2525B
- [ ]  It is very probably an issue in APP6-D (symbol appears in standard)

It is not an issue in APP6-B.

One of two issues from https://github.com/Esri/military-symbology/issues/270 - This one is a label issue.
This should allow us to get on with finishing up 270.

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 45110202 | Pressure Systems-High Pressure Center-Tropopause High | Atmospheric Point |

![image](https://user-images.githubusercontent.com/3801392/45444906-c8804800-b696-11e8-9945-44ac864a3962.png)

Should be:
![image](https://user-images.githubusercontent.com/3801392/45444943-e8177080-b696-11e8-8d7c-4593b3bbda83.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#73
