### ISSUE TITLE
Ice Drift (Direction) symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#296]
This is an issue in:
- [ ]  2525C
- [ ]  2525B

It is not an issue in APP6-B, APP-6-D
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 46110304 | Ice Systems-Dynamic Processes-Ice Drift (Direction) | Oceanographic Point |

![image](https://user-images.githubusercontent.com/3801392/45511877-2c287500-b76c-11e8-95dc-c1059d0c2e13.png)

Should be:
![image](https://user-images.githubusercontent.com/3801392/45511904-42363580-b76c-11e8-9017-74679be30e85.png)

**Comment by BobBooth** [comment]
Symbol Key lacked _C suffix. Added a copy with that value. Testing to see if this resolves the issue.

**Comment by BobBooth** [comment]
The symbol now appears as an arrow.  I tested whether the symbol rotates when the rotation angle is specified, and it does not.
![image](https://user-images.githubusercontent.com/3801392/45765824-fff57400-bc03-11e8-87bf-93559f53e591.png)
According to the 2525B doc, "3. Orientation. The orientation of the graphic points in the direction of the ice drift." (p654)
@csmoore - how would we modify the style to apply rotation?

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#75
