### ISSUE TITLE
Fish Weirs symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#297]
This is an issue in:
- [ ]  2525C
- [ ]  2525B

It is not an issue in APP6-B, APP-6-D
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 46120310 |Hydrography-Ports and Harbors- Fish Wiers (Point) | Oceanographic Point |

![image](https://user-images.githubusercontent.com/3801392/45512256-40b93d00-b76d-11e8-8116-55154bb0c077.png)

Should be:
![image](https://user-images.githubusercontent.com/3801392/45512271-4f9fef80-b76d-11e8-836b-f8c8cdcf5197.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#76
