### ISSUE TITLE
Kelp (point) symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#298]
This is an issue in: 
- [ ]  2525C
- [ ]  2525B

It is not an issue in APP6-B, APP-6-D
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 46120506 | Hydrography-Dangers/Hazards-Kelp/Seaweed (Point) | Oceanographic Point |

![image](https://user-images.githubusercontent.com/3801392/45512388-9aba0280-b76d-11e8-878f-7a519410718f.png)

Should be:
![image](https://user-images.githubusercontent.com/3801392/45512410-a7d6f180-b76d-11e8-8638-940618051170.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#77
