### ISSUE TITLE
Trough axis (line) symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#299]
This is an issue in:
- [ ]  APP-6-D

This is not an issue in 2525C, and 2525B.
It is not an issue in APP6-B.
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 45110401 | Pressure Systems-Lines-Trough Axis | Atmospheric Line |

Solid line, should be dashed.

Should be:

![image](https://user-images.githubusercontent.com/3801392/45513060-a8708780-b76f-11e8-9597-9c4584d988c8.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#78
