### ISSUE TITLE
Pressure Systems-Lines-Convergance Line symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#300]
This is an issue in:
- [ ]  2525C
- [ ]  2525B
- [ ]  APP-6-D.

It is not an issue in APP-6-B.
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 45110408 | Pressure Systems-Lines-Convergance Line | Atmospheric Line |

![image](https://user-images.githubusercontent.com/3801392/45513285-49f7d900-b770-11e8-860f-18b434af3967.png)

Should be:
![image](https://user-images.githubusercontent.com/3801392/45513330-6136c680-b770-11e8-8bc9-ee6ce3574cb8.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#79
