### ISSUE TITLE
Isopleths-Operator Defined-Freeform symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#301]
This is an issue in:
- [ ]  2525C
- [ ]  2525B.
- [ ]  APP-6-D.

It is not an issue in APP-6-B.
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 45180700 | Isopleths-Operator Defined-Freeform | Atmospheric Line |

Draws dashed, solid option not available
Should be:

![image](https://user-images.githubusercontent.com/3801392/45513827-c63eec00-b771-11e8-8a3d-15f874851a9c.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#80
