### ISSUE TITLE
Hydrography-Dangers/Hazards-Reef symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#302]
This is an issue in:
- [ ]  2525C
- [ ]  2525B

It is not an issue in APP-6-B or APP-6-D.
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 46120512 | Hydrography-Dangers/Hazards-Reef | Oceanographic Line |

Preview is right (jagged line), but actual line drawn on map is just straight.
![image](https://user-images.githubusercontent.com/3801392/45514074-64cb4d00-b772-11e8-85fd-4c199326182b.png)

Should be:

![image](https://user-images.githubusercontent.com/3801392/45514101-77458680-b772-11e8-81af-488589cfd506.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#81
