### ISSUE TITLE
Weather Symbols-Tropical Storm Systems-Tropical Storm Wind Areas and Date/Time Labels symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#303]
This is an issue in: 
- [ ]  2525C
- [ ]  2525B.
- [ ] APP-6-D.

It is not an issue in APP-6-B.
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 45110408 | Weather Symbols-Tropical Storm Systems-Tropical Storm Wind Areas and Date/Time Labels | Atmospheric Area |

![image](https://user-images.githubusercontent.com/3801392/45514276-ecb15700-b772-11e8-8b0e-77833d12f2c7.png)

Should be:

![image](https://user-images.githubusercontent.com/3801392/45514317-0ce11600-b773-11e8-82b9-0cb0ba38917a.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#82
