### ISSUE TITLE
Bounded Areas of Weather-Operator Defined-Freeform symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#304]
This is an issue in:
- [ ]  2525C
- [ ]  2525B
- [ ]  APP-6-D

It is not an issue in APP-6-B.
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 45171000 | Bounded Areas of Weather-Operator Defined-Freeform | Atmospheric Area |

Only dashed option draws - should have operator option to draw a solid black line or a dashed black line.

Should be:
![image](https://user-images.githubusercontent.com/3801392/45558373-c42a6b00-b80d-11e8-9df3-87229fdacf83.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#83
