### ISSUE TITLE
Hydrography-Dangers/Hazards-Kelp/Seaweed (Area) symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#305]
This is an issue in: 
- [ ] 2525C
- [ ] 2525B

It is not an issue in APP-6-B or APP-6-D.
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 46120507 | Hydrography-Dangers/Hazards-Kelp/Seaweed (Area) | Oceanographic Area |

Symbol does not draw, preview is yellow quatrefoil.
![image](https://user-images.githubusercontent.com/3801392/45558680-7c581380-b80e-11e8-9230-c6de1d8485ab.png)

Should be:
![image](https://user-images.githubusercontent.com/3801392/45558731-985bb500-b80e-11e8-9e1d-1fb8ac385012.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#84
