### ISSUE TITLE
Bounded Areas of Weather - Marginal Visual Flight Rule (MVFR), (Area) symbol issue

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#306]
This is an issue in:
- [ ] 2525C
- [ ] 2525B.
- [ ] APP-6-D

It is not an issue in APP-6-B.
It is fixed in 2525D (https://github.com/Esri/military-symbology/issues/270)

| **Fixed** | **SIDC** | **Name** | **Feature Type** |
| --- | --- | --- | --- |
| <ul><li>\- [ ] </li></ul> | 45170200 | Bounded Areas of Weather - Marginal Visual Flight Rule (MVFR), (Area) | Atmospheric Area |

Draws solid blue line, not scalloped.

Should be:
![image](https://user-images.githubusercontent.com/3801392/45558951-26d03680-b80f-11e8-8220-9ef6b2970f77.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-symbology-styles#85
