### ISSUE TITLE
Military Symbol Editor GUI text edits

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#320]
A few proofreading issues from the MSE GUI

1. When you first open the Military Symbol Editor pane, the Search box says:
Please click to enable addin...
**add-in** should be spelled with a hyphen.

2. There is a notification/status text in the lower right corner that says:
Addin Not Enabled (2525D)
This should also have a hyphen.
![image](https://user-images.githubusercontent.com/3801392/47579923-6d8b7300-d91b-11e8-8ea1-d703271b14b3.png)

3. After you click the text "Please click to enable addin..." a message pops up titled "Add-in Disabled" (this one is spelled correctly). 
![image](https://user-images.githubusercontent.com/3801392/47580423-d9221000-d91c-11e8-8a00-63d4469ee3d9.png)

The message is:
The Military Symbol Editor requires the Military Overlay data model.
Would you like to add the data model (database schema and layers to the TOC) to the project?.
Yes   No

3a. There is an extra period at the end of the second sentence.  
3b. I suggest changing the second sentence to:
Add the database schema and layers to the project?
Yes   No

**Comment by csmoore** [comment]
PR #329 Created

**Comment by dfoll** [comment]
- ArcGIS Pro 2.3 MSE 26 Commercial\Solutions\DefenseSolutions\MilitarySymbolEditor\January2019\Dev\26
   - 
- ArcGIS Pro 2.3 MT
