### ISSUE TITLE
Military Symbol Editor not returning results for search in METOC category

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#323]
With the 12/18 MSE build and Pro 2.3.0 daily, using 2525B symbology I'm seeing some most METOC keywords not return any symbol matches, when I would expect to see some.
For example, no results searching for:
metoc
METOC
Hydrography
Beach
Depth
Kelp
Sediments
Ice edge
Ice system
Ispopleth
Pressure systems
Winds
Cloud
Snag
Anchorage
Tide
Ice Systems (though Iceberg does show up)
Icing
Lighthouse
Turbulence
Volcanic Eruption (though Natural Event: Geologic : Volcanic Threat does show up)
Drizzle
Rain
Lightning
Thunderstorm
Tropical Storm
Hurricane

**Comment by csmoore** [comment]
I do see what is going on here, the METOC keys have a slightly different format/length (13) in the new styles so we just need to included these in the search.

**Comment by csmoore** [comment]
Addressed in PR #325 METOC symbols (and others) missing from search.  Also in new style format, the SIDC had moved from tags to key field so this affected a number of non-METOC symbols as well.

There were a couple of things going on here, the tags/keys format changed at 2.3 and there is a new problem discoverd with creating METOC exports recorded here https://github.com/ArcGIS/military-symbology-styles/issues/144 that required a workaround.

**Comment by BobBooth** [comment]
@csmoore - I  built your branch using the MSE testing pipeline and tested - the 2525B METOC symbols are now being returned by the MSE search.

**Comment by BobBooth** [comment]
Removing Manual Verify tag.
