### ISSUE TITLE
MSE coded value domains cannot be cleared once chosen

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#330]
This is an ease-of-use feature enhancement suggestion.  Some of the attributes that you can set from the Symbol and Label tabs in MSE are populated using a dropdown list control limited to a coded value domain.  If you choose a value from one of these, you can change it to one of the other domain values, but you cannot reset it to Null status.
I noticed this using APP6-D Dismounted Individual symbols, where the echelon that the individual belongs to is noted inside the frame, rather than outside of it, and stored in the Modifier 1 field.  I tried to clear the main echelon field, which I had set earlier.  I found that it was impossible - I could change to another echelon, but not remove it entirely.
It would be nice to have another row in the dropdown list, that, if chosen, would reset the field to null, like the core Attribute Editor does:
![image](https://user-images.githubusercontent.com/3801392/50993640-32471c00-14e8-11e9-9831-0a0c25d5775a.png)

The current way to get around this would be to search for a new symbol, choose it, then search for the base symbol that you were using before and take up customizing it from scratch.  This is less convenient than being able to simply clear the field completely (it might also be useful to allow a "Delete" key press and/or "Backspace" key press to clear the field when it is selected).

**On the Symbol tab:**
Identity/Affiliation
Status/Planned
FT, FD, HQ
Echelon
Context
Modifier 1
Modifier 2

**On the Label tab:**
Reinforced
Credibility
Reliability
Country Code

**Comment by csmoore** [comment]
Updated PR #346 - Allow setting field with domains attached to null. Should look like this now:

![image](https://user-images.githubusercontent.com/3090809/52136097-4c6ea880-2615-11e9-9cf2-4b2edc275206.png)

Note: There were a couple fields that I did not allow to be nulled out because they would cause problems with the addin. These fields are affiliation/identity, symbolentity, and functioncode, but these are ones the user would not expect to be able to null out.

**Comment by BobBooth** [comment]
Built from Dev, tested with 2525Bc2, 2525D, and APP-6(D) on Pro 2.3.
Works!

**Comment by BobBooth** [comment]
Updated doc. This now appears in the Issues Addressed table for the March 2019 Resources page. Tab Nav is working correctly.

**Comment by BobBooth** [comment]
Moved to impeded because of tab nav issue - cannot navigate from Getting Started or Workflows to March 2019 Release page.  I have tried updating the config file, the maps for each tab, and the pubs for each tab, and republished.  The March 2019 Release page is there, you can get to it from the Home page for MSE. You can also navigate from the March 2019 Release page to Getting Started or Workflows - you just can't navigate back using the tabs.
