### ISSUE TITLE
MSE string length feedback should fade out after flashing red

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-symbology#331]
We have implemented a cap on the number of characters that can be entered in the MSE to match the field lengths in the database schema.  As you type after this limit, no further characters are added. This is good. See https://github.com/Esri/military-symbology/issues/327

The way it is now working, the box gets a red outline and a hovertext pop-up indicating that the field has reached the maximum limit. 
You can add the maximum number of characters to several boxes, and they all stay outlined in red.
This seems like an unnecessary level of "warning" hanging around.  The field length is only relevant as you are actually typing/attempting to exceed it.  

I suggest that when you hit the first character above the limit, the box will highlight in red, but then fade back to the default color (maybe over 2 seconds or so). Type more in the box, and it goes back red, refuses input, then fades out again. The hovertext should still appear when you hover over the box at max capacity.
This way, the feedback is tied directly to the action (attempting to cram additional characters in the field once it is maxed out) but once you move on, you are not left with a bunch of reminders that these fields are at their max limits.

**Comment by kgonzago** [comment]
Current implementation of displaying max allowable length:
![image](https://user-images.githubusercontent.com/6391826/51278067-8bf78c80-19a7-11e9-983c-013f3923e54c.png)

This implementation was accepted by the team during sprint 16 review (1/18).
