### ISSUE TITLE
Support 2525C in MSE 

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#332]
### Background
Esri Japan reported that the MSE does not indicate support for 2525C.

### Expected Result
The MSE allows the user to select 2525C. 
The underlying dictionary supporting 2525B Change 2 also supports 2525C.

**Comment by csmoore** [comment]
There is an existing layer package with the 2525C datamodel at: https://github.com/Esri/military-features-data/tree/dev/military-overlay/mil2525c/lpkx so most of the work should be in the Military Symbol Editor:

1. Check the 2525 layer package
2. Adding the 2525C option to the standard selection
3. Adding a check if the 2525C datamodel already exists in the project - 2525C will have a "Stability | Activities layer (EMS symbols) that 2525B lacks so that is probably how we will have to differentiate 
4. Testing 2525C + checking that nothing breaks with 2525B

**Comment by BobBooth** [comment]
I manually added the first 10 points in the 2525C standard for Appendix G by adding a Stability: Activities point and editing the Extended Function Code and Affiliation fields.  The symbols displayed as expected.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/41e11910-e12d-4d2e-ad6f-9ec6db2a15c5)
I then added the Appending G points feature class from the CCompleteTestData.gdb (extracted from the Mil2525-C-CompleteTestData.ppkx in \GitHub\military-features-data\military-symbology-styles\test-data\mil2525c\pro-projects
I set the symbology for the layer using the Dictionary renderer and chose the 2525C dictionary option. I used the Full SIDC field to symbolize the layer.
The points were symbolized on the map and appear to be good.  There was a "Bridge" symbol that was drawing with the inverted question mark with the red X through it. No other points had this or "unknown" symbols.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/0f7ff0d7-cc6b-46c5-9313-ba7614942e93)

**Comment by csmoore** [comment]
@BobBooth - that may be an error in the test data having that G-M-BCB--- symbol as a point, in the Tactical Graphic section it shows it as a line (which is what I would also expect): 

![image](https://user-images.githubusercontent.com/3090809/55360876-9eac3880-54a3-11e9-96e9-503a3cc49c9f.png)

**Comment by BobBooth** [comment]
@csmoore - I agree, that is an error in the test data.  Should not be a point. We do have line feature "bridge" type in the Control Measure Lines feature class, and they are drawing correctly there.

**Comment by BobBooth** [comment]
The updated 2525C LPKX is in this (now merged) [PR](https://github.com/Esri/military-symbology/pull/360).

**Comment by csmoore** [comment]
Work on the addin to support this change has started in branch: https://github.com/Esri/military-symbology/tree/csm-332-add-2525C-support 

This is taking a little more time than expected - there is an existing startup sequence that (1) tries to determine if the project already has the required schema that matches a standard, and (2) then sets the addin symbol standard to that, that will probably need to be refactored. There are 2 problems with the existing method:

1. Its scans the project, checks for a GDB that contains every feature class, doing this 4 times on startup will lead to poor performance
2. The feature class schemas, which were being checked, are identical for 2525C and 2525Bc2, so some other difference will need to be identified for these

I beleive we will need to change this - for now - I was going to change this sequence to look for the featuredataset name that differs, and is unique, with each standard (ex. "militaryoverlay2525d")

**Comment by dfoll** [comment]
@BobBooth please review
### Doc updates
- [PR](https://github.com/ArcGIS/arcgis-solutions-website/pull/7729) waiting for review/merge for website updates
- cms changes on are DEV
   - https://solutionsdev.arcgis.com/defense/help/military-symbol-editor/resources/june-2019-military-symbol-editor.htm
   - https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- pdf are included in new builds that were kicked off
   - \\...\DefenseSolutions\MilitarySymbolEditor\Dev\93\
   - \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\263\

**Comment by BobBooth** [comment]
@dfoll - reviewed contents on soldev - looks good. Could not access PDF location due to server issue.

**Comment by BobBooth** [comment]
@dfoll - able to get to server now.  Updates present in PDFs.
