### ISSUE TITLE
Remove xceed wpf toolkit dependency 

### ISSUE THREAD

**Issue by jmccausland** [Esri/military-symbology#333]
@nfeuerstein @lfunkhouser @csmoore @kgonzago  Looks like the symbol editor is the only military tool that has a dependency on the xceed wpf toolkit.  If I were to do the work to replace the "DateTimePicker" and "ShortUpDown" controls, could we get this in before the 25th release?

![image](https://user-images.githubusercontent.com/5815558/51209722-e8db4000-18de-11e9-94eb-11f278804226.png)

**Comment by lfunkhouser** [comment]
@jmccausland - Thank you. We would appreciate the contribution and yes, we would get this released with the new version. Would it be possible to shoot for 1/21 in order for the team to test?

**Comment by jmccausland** [comment]
I'm hoping to have a PR for this today.

**Comment by lfunkhouser** [comment]
Tested dev build 3.3.0.195
Verified functionality on Pro 2.1. Chose 1/23/2019 and manually entered 14:03 for time:
![image](https://user-images.githubusercontent.com/3800729/51642647-c8cf0080-1f1e-11e9-913d-fc3307ff5b0d.png)
![image](https://user-images.githubusercontent.com/3800729/51642652-cc628780-1f1e-11e9-8814-bafcea53eb4a.png)

Verified functionality on Pro 2.3. Chose 1/23/2019 and 14:03 in the picker:

Doc tested for workaround/known issue for time in Pro 2.1. 
-   Verified website pages for Military Tools and Military Symbol Editor on dev
-   Verified doc updates in PDFs of MT (build 195) and MSE (build 36)
