### ISSUE TITLE
January 2019 Release notes Known Issues section - refers to issue with Modify Tab

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#336]
The Modify tab has been removed from the MSE. Remove the "Modify tab is not working with cleared labels" bullet point under Known Issues.

**Comment by BobBooth** [comment]
Removed from both MSE release page and MT Release page, republished from CMS the solutions pages and the PDFs. Rebuilt both MSE and MT from Dev and checked MSE and MT PDFs; the bullet point has been removed from both.

**Comment by lfunkhouser** [comment]
Verified as fixed on dev versions. Closing.
