### ISSUE TITLE
Update doc to be standard agnostic

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#343]
Customize a symbol topic is written with 2525D/APP6D in mind. 
https://solutions.arcgis.com/defense/help/military-tools/workflows/customize-a-symbol.htm

Some of the drop-down lists stated in Step 2 don't apply to 2525B Change 2.

**Comment by dfoll** [comment]
### Doc updated at:
- https://solutionsdev.arcgis.com/defense/help/military-symbol-editor/workflows/customize-a-symbol.htm
- https://solutionsdev.arcgis.com/defense/help/military-symbol-editor/workflows/customize-labels.htm
- https://solutionsdev.arcgis.com/defense/help/military-tools/workflows/customize-a-symbol.htm
- https://solutionsdev.arcgis.com/defense/help/military-tools/workflows/customize-labels.htm
- Commercial\Solutions\DefenseSolutions\MilitarySymbolEditor\Dev\96
-
