### ISSUE TITLE
Selecting a symbol with a label set to max field length is causing selection to fail

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbology#345]
Selecting a symbol which has a label set to the maximum field length causing is causing the selection to fail (not crash, just fails to enable the Save Edits button).

For example, if a symbol is selected which has a UniqueDesignation string length of 30, the Unique Designation field on the label tab is not set correctly and the "Save Edits" button is not activated as it should.

Repro steps:

1. Search for a new symbol to create a new symbol
2. On the label tab set the Unique Designation to the max allowable length (30) or enter data until you get the warning
3. Add the symbol to the map
4. Search for another symbol (so the previous symbol is cleared, a new symbol preview is shown, fields are cleared)
5. Using the Selection Tool (beside "Select a Feature To Modify"), attempt to select the symbol with Max Label length
6. The Unique Designation field on the label tab is not set correctly and the "Save Edits" button is not activated as it should

![image](https://user-images.githubusercontent.com/3090809/52010615-faf2dc00-24a3-11e9-944c-444c5921a401.png)

Cause: the exception that was added recently to validate the label to let the UI know validation failed is also occurring during selection and requires some extra checks added.

**Comment by csmoore** [comment]
Addressed in PR #347

**Comment by BobBooth** [comment]
I built from the test branch and tested locally on Pro 2.3.  It worked fine.  Was able to add text out to the length of the field, get the "warning" flag, add that symbol to Favorites, add multiple symbols to the map, interactively selected them on the map. Tested using 2525D standard.

**Comment by BobBooth** [comment]
Built from Dev, tested with 2525Bc2, 2525D, and APP-6(D).
Works!

**Comment by BobBooth** [comment]
March 2019 Resources page is publishing to Dev, but tab nav is broken from the CMS sourced pages to each other.

**Comment by BobBooth** [comment]
Tab navigation on Dev is fixed. The document map version had to be updated in the Getting Started and Workflows publication files. Now they are publishing correctly and the navigation works.

**Comment by BobBooth** [comment]
Moved to impeded because of tab nav issue - cannot navigate from Getting Started or Workflows to March 2019 Release page.  I have tried updating the config file, the maps for each tab, and the pubs for each tab, and republished.  The March 2019 Release page is there, you can get to it from the Home page for MSE. You can also navigate from the March 2019 Release page to Getting Started or Workflows - you just can't navigate back using the tabs.
