### ISSUE TITLE
Update schema to support text modifiers - Signature Equipment and Country Indicator

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#353]
The data model is missing the necessary fields in order for Pro to support these in the dictionary. 

There are some text modifiers that can not be mapped in the UI and are missing from the label symbols. These are:

- [x] Signature Equipment (L)
- [x] Country Indicator (AS) - this will be added to Activities for now but will potentially be included for other symbol sets in the future
Activities:
image
![image](https://user-images.githubusercontent.com/3800729/54134832-e294ac00-43d5-11e9-8750-3452d565cace.png)

Land:
image
![image](https://user-images.githubusercontent.com/3800729/54134842-e7596000-43d5-11e9-8168-1d5f518b35e0.png)

**Comment by jeconley** [comment]
@lfunkhouser I am going to go ahead and add these new labels to the style and script because we have several changes to install.  I am going to add them as "signatureequipment" and "countryindicator" in the script.  Please let me know if you want them to be something else.  We would need to change them before the end of the release.

**Comment by csmoore** [comment]
@jeconley - sorry I didn't reply to earlier, the current schema has fields

[countrycode](https://github.com/Esri/military-features-data/blob/dev/military-overlay/utils-source-and-test-data/schema-source-files/mil2525d/military_feature_schemas/Fields_Activities.csv#L24) (differs from what you have above)

[signatureequipment](https://github.com/Esri/military-features-data/blob/dev/military-overlay/utils-source-and-test-data/schema-source-files/mil2525d/military_feature_schemas/Fields_LandEquipment.csv#L17) (this matches what you have above)

If you use those we can test with the existing layer packages

**Comment by jeconley** [comment]
Thanks @csmoore.  I will use those names.

**Comment by csmoore** [comment]
Note: this issue is also related to #363 and from that issue the "Country Indicator (AS)" is to be called "countrylabel"

**Comment by dfoll** [comment]
- [ ] APP6-B
- [ ] APP6-D
- [ ] MIL-STD-2525Bc2
- [ ] MIL-STD-2525C
- [ ] MIL-STD-2525D

**Comment by dfoll** [comment]
### New .lpkx creation
- [ ] 2525D
- [ ] 2525C
- [ ] 2525Bc2
- [ ] APP6D
- [ ] APP6B

**Comment by dfoll** [comment]
updates to all .lpkx files in #382

**Comment by dfoll** [comment]
Based upon my best interpretation of the five standards we currently support, with the changes in #385  we support what the standards explicitly state for Signature Equipment and displaying the country name. 

For labeling requests that go beyond what is specified by a particular standard, new issues will need to be created

**Comment by dfoll** [comment]
this was taken care of in #382 

- [x] add to mse oct resources
- [ ] add to mt oct resources
- [ ] add to def what's new

**Comment by dfoll** [comment]
### Doc review:
- [ ]  [Military Symbol Editor October resources](https://solutionsdev.arcgis.com/defense/help/military-symbol-editor/resources/october-2019-military-symbol-editor.htm)
- [ ] \DefenseSolutions\MilitarySymbolEditor\October2019\Dev\144\
- [ ]  [Military Tools October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\320\
- [ ]  [What's new page](https://solutionsdev.arcgis.com/defense/what-is-new/) updated in [PR 7973](https://github.com/ArcGIS/arcgis-solutions-website/pull/7973)

**Comment by csmoore** [comment]
Verified:
 
1. MSE October Resources - bug added to table
2. MSE homepage - Added to Releases Table
3. MSE .pdf - bug added to table
4. Military Tools October Resources - bug added to Issues addressed
5. Military Tools for ArcGIS Release Notes.pdf - bug added to table
6. Defense What's new - MSE added to October 2019
