### ISSUE TITLE
Support for Direction of Movement Indicator

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#354]
https://devtopia.esri.com/ArcGISPro/multiscale-mapping/issues/845

Brief Overview :
As a user I should be able to indicate the direction of movement on a symbol using the direction of movement amplifier.

For Land symbols this is an angled arrow extending downward from the bottom of the frame and pointing in the direction of movement
For all other symbols, it is an arrow extending from the center of the frame/icon and pointing in the direction of movement

Design :
A new field will be added to the data model. Users can map to a field that contains the angle and an override on the arrow will update the direction.

**Comment by jeconley** [comment]
@lfunkhouser I have a working version of the direction of movement symbol.  In the script I currently have it as "directionofmovement".  We have several changes we would like to get installed so we will move forward with that.  Please let me know if you want it to be something else.  We would need to change it before we ship.

**Comment by csmoore** [comment]
@jeconley - sorry I didn't reply to earlier, the current schema has a field ["direction"](https://github.com/Esri/military-features-data/blob/dev/military-overlay/utils-source-and-test-data/schema-source-files/mil2525d/military_feature_schemas/Fields_Units.csv#L22) - if you use that we can test with the existing layer packages 

[Currently schema example](https://github.com/Esri/military-features-data/blob/dev/military-overlay/utils-source-and-test-data/schema-source-files/mil2525d/military_feature_schemas/Fields_Units.csv)

**Comment by jeconley** [comment]
Thanks @csmoore.  I will update the script.

**Comment by lfunkhouser** [comment]
#353 should be done prior to updating layer packages for this issue.

**Comment by dfoll** [comment]
- [ ] add to mse oct resources
- [ ] add to mt oct resources
- [ ] add to def what's new

**Comment by dfoll** [comment]
### Doc review:
- https://solutionsdev.arcgis.com/defense/help/military-symbol-editor/resources/october-2019-military-symbol-editor.htm
- \DefenseSolutions\MilitarySymbolEditor\October2019\Dev\144\
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm
- \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\320\
- What's new page updated in [PR 7973](https://github.com/ArcGIS/arcgis-solutions-website/pull/7973)

**Comment by csmoore** [comment]
Verified:
 
1. MSE October Resources - bug added to table
2. MSE homepage - Added to Releases Table
3. MSE .pdf - bug added to table
4. Military Tools October Resources - bug added to Issues addressed
5. Military Tools for ArcGIS Release Notes.pdf - bug added to table
6. Defense What's new - MSE added to October 2019

Additional Note: switched fixed at version to Pro 2.4 - since it requires that version (with DictionaryRenderer changes) to see this indicator
