### ISSUE TITLE
Create APP6B Schema + lpkx

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#362]
Needed for Pro 2.4 implementation of APP6B

Tasks:

- [x] Create a folder to define the schema input for features, fields, domains [similar to this one for 2525C](https://github.com/Esri/military-symbology/tree/dev/military-overlay/utils-source-and-test-data/schema-source-files/mil2525c)
  - [x]  schema & domain  .csv files
      - [x] Air
      - [x] Space
      - [x] Units
      - [x] LandEquipment
      - [x] Installations
      - [x] ControlMeasuresPoints
      - [x] ControlMeasuresLines
      - [x] ControlMeasuresAreas
      - [x] SeaSurface
      - [x] SeaSubsurface
      - [x] Activities 
      - [x] METOCPoints
      - [x] METOCLines
      - [x] METOCAreas
   - [x] schemas.csv
- [x] Add/change new additional attributes to layers that are being added for Pro 2.4 
    - [x] - civilian: boolean
    - [x] - countrylabel - string
    - [x] - change `iff_siff` to `idmode` (to be consistent with the other standards)
- [x] Generate the GDB from this schema input using the existing utlities
- [x] Create the layer package that uses this schema (`*` ~~Important, there will not be a dictionary renderer yet to work with this schema so you may have to initially attach 2525C/Bc2 to get something to draw for now~~) 
    - [x] Create layers and check metadata
    - [x] Add Create Feature Templates
    - [x] Create and test lpkx

**Comment by dfoll** [comment]
### gdb creation process
- [ ] Air
- [ ] Space
- [ ] Units
- [ ] LandEquipment
- [ ] Installations
- [ ] ControlMeasuresPoints
- [ ] ControlMeasuresLines
- [ ] ControlMeasuresAreas
- [ ] SeaSurface
- [ ] SeaSubsurface
- [ ] Activities
- [ ] SIGINT
- [ ] METOCPoints
- [ ] METOCLines
- [ ] METOCAreas

**Comment by BobBooth** [comment]
PR with the files: https://github.com/Esri/military-symbology/pull/366

**Comment by dfoll** [comment]
Moved to Impeded because we do not have a dictionary renderer that supports drawing attributes from this schema

**Comment by csmoore** [comment]
Added tasks for adding attributes: civilian: Boolean, countrylabel - string to original issue

**Comment by csmoore** [comment]
The attribute-based military overlay GDB has been generated from the source data in [this dev branch](https://github.com/Esri/military-symbology/tree/bb_362_start_app6b_schema)

![image](https://user-images.githubusercontent.com/3090809/57081672-38dde700-6cc3-11e9-8fb6-0dbacf34f07f.png)

The updated attribute-based APP-6(B) dictionary renderer is now available in the Pro 2.4 daily install and the layer package is ready to be created for this (working on that next).

**Comment by csmoore** [comment]
Creating the layers and templates is complete, just need to test the packaging/unpackaging. 

![image](https://user-images.githubusercontent.com/3090809/57104552-a48d7780-6cf6-11e9-848a-83e47e8cf581.png)

The only issue I have noticed so far is that a couple of the Tactical Graphics names are not very descriptive (about 8 names) - but these names were right from the Tactical Graphics SIDC Table B-IX - not sure if we need to correct these :

![image](https://user-images.githubusercontent.com/3090809/57100885-009fce00-6cee-11e9-9ba2-31a2f710fac1.png)

**Comment by csmoore** [comment]
The attribute-based app6b layer package [was added to here](https://github.com/Esri/military-symbology/tree/bb_362_start_app6b_schema/military-overlay/app6b/lpkx). This also includes the corrections to the unclear Control Measure names noted above.  This should complete the dev work and this should be ready to verify (Note: requires latest/daily Pro 2.4).

**Comment by csmoore** [comment]
I noticed a few lpkx layers were missing metadata - so fixing that now.

**Comment by dfoll** [comment]
doc for this issue should done with #373
