### ISSUE TITLE
Update .lpkx to support displaying country

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbology#363]
### Background
Current implementation of the .lpkx using Military Symbol Editor country codes are not displaying correctly.

## Update layer packages to display country for 2.4
- Add field ~countryname~ --> `countrylabel` 
   - Alias ~~Country Name~~ `Country Label`
   - **Decision needed on how to populate** `countrylabel`
      - Field is displayed on MSE UI, free text entry by user
      - String field populated by the description from the domain for `countrycode`
      - Note : these labels/fields are only shown on 2525D and APP6D and later standards (not ealier standards) so do not need added to the earlier standards.

## Update layer packages to support displaying country post-2.4
- Field `countrycode` _already exists in schema_
   - Alias `Country Code`
   - Coded value domains
      - Value is from the SIDC appropriate to that standard, for example:
         - Value: 840 -> Description: United States (2525D/APP6D - 3rd 10)*
         - Value: US -> Description: United States (2525B/C/APP6D - 13,14 digits)*

\* Values should match the values in the SIDC
** Code used in the style to encode the country icon/vector/flag 
*** Potential configuration setting to display either label or icon

## Notes/Outstanding questions
- When is the correct place to use GENC -vs- ISO _some countries are recognized differently between the two_
- Can we use attribute rules and version GDB (2.4) to keep `countryname` and `countrycode` in sync _this may break backwards compatibility for .gdb_
- Does 2-letter -vs- 3-letter code factor in 
- Work for 2.4 is still useful post-2.4 ... possible dual display of flag (driven by `countycode`) and name or other designator driven by `countryname`)

**Comment by csmoore** [comment]
@jeconley @dfoll - is there any chance we could change the first field/attribute to **countrylabel** instead of **countryname** 

I think this small change will better convey to the user who looks at the feature class design that this attribute is a free-form label only (and we would also document it as such).

I'm just afraid when we show the user the country name domain values for the **countrycode** field (like we do both now and in the future), this might be confusing when they also see a field called "countryname"

![image](https://user-images.githubusercontent.com/3090809/55875367-ef3a2a80-5b62-11e9-8216-a4bcf9804224.png)

**Comment by dfoll** [comment]
I'm ok with it.

**Comment by jeconley** [comment]
We originally discussed it being countrylabel but decided on countryname in the meeting.  Please send an email to MilitarySymbology@esri.com and purpose changing it to countrylabel with the reasons why.  If they sign off we can go with that.  I just need to know so I can update the script.

**Comment by lfunkhouser** [comment]
Good point, @csmoore. I am good with `country label` over `country name` to avoid potential confusion with the already used country name for the domain values.

**Comment by csmoore** [comment]
Quick note/update - the MilitarySymbology email alias was OK with the attribute name change ( ~countryname~ -->  `countrylabel` ) so the original issue has been updated. 

I also added a note that the `countrylabel` attribute label is only shown on 2525D, APP6D, and later standards so do not need added to the earlier standards.

**Comment by jeconley** [comment]
@csmoore I believe it was decide that we would add it to the other standards.  I was planning on updating the label to have it in the same location as it is in D.  @lfunkhouser is this correct?

**Comment by csmoore** [comment]
While we are updating the GDBs/LPKXs this sprint we would like to go ahead and make these countrylabel/countrycode changes, specifically:

1. Adding the CountryLabel text attribute to all feature classes/standards
2. Updating CountryCode to match the country coding method referenced in the standard (and used in the SIDCs for all except 2525D):

- [ ] APP6D - **ISO 3166** 3-Digit Numeric (Very Similar to GENC) (ex. US = "840") 
- [ ] 2525D - **GENC** 3-Digit Numeric (Very Similar to ISO 3166) (ex. US = "840") (see Note: `*`)
- [ ] 2525C - **ISO 3166** 2-Character Alpha  (ex. US = "US")
- [ ] 2525B - **FIPS Pub 10 series** 2-Character Alpha (Same as APP6B) (ex. US = "US")
- [ ] APP6B - **FIPS Pub 10 series** 2-Character Alpha (Same as 2525B) (ex. US = "US")

`*` Note: 2525D references the GENC standard but does not state whether the encoding is alpha or numeric 

@jeconley @joebayles - just wanted to confirm this encoding/change is what you are expecting

**Comment by dfoll** [comment]
In my opinion, this one does not need to be explicitly documented. Documentation of what this work covered was done under #353

**Comment by dfoll** [comment]
Removing the T labels, because even as the original author of the issue I am not sure why they were there. The issue body does not reference what specific standards this was written for. With the work for issue #353 covered by pr #382 the guidelines for how the standards should display country are followed to the best guidance of the standard. Any exact requests for deviation from what the standard expressly states should be entered as new issues stating exactly what standard(s) and layers it is being requested for.
