### ISSUE TITLE
The military style for 2525B change 2 is not found in Pro Install

### ISSUE THREAD

**Issue by jmccausland** [Esri/military-symbology#371]
@BobBooth  When selecting 2525B change 2 as the military style I get the following error.

![image](https://user-images.githubusercontent.com/5815558/56760132-8c52b100-6768-11e9-95f7-559ecd5ed0d6.png)

**Comment by jmccausland** [comment]
There may have been some core changes in this area that is causing the issue.

**Comment by csmoore** [comment]
On the Pro 2.4 daily install around 4/20 the dictionary name was changed from `mil2525c_b2` (that was used previously for both 2525C and 2525B) to separate dictionaries for each named `mil2525c` and `mil2525bc2` - this change just needs updated in the code

**Comment by csmoore** [comment]
This fix was added in PR #372

**Comment by dfoll** [comment]
I have an old version of Pro that still installs the old dictionary `mil2525b_c2` so i did not see this problem until I installed @csmoore fix for this and then saw the problem ... code was looking for `mil2525b` or `mil2525c` and installed dictionary was `mil2525c_b2` (essentially testing backwards of how @jmccausland found this...
i will now install a newer version of pro 2.4 that has the updated dictionary names and confirm that error is no longer displayed.

**Comment by dfoll** [comment]
### Testing PR #372 I saw some weird behavior
- installed Pro 2.4 build 19590
- this installed a dictionary specific for 2525C
![image](https://user-images.githubusercontent.com/5322669/57390978-865ac800-718b-11e9-86c6-9a29996b68ef.png)
- the dictioinary for 2525B was installed as "mil2525bc2"
![image](https://user-images.githubusercontent.com/5322669/57391056-a7bbb400-718b-11e9-8000-de45c003287f.png)
**at this point that is not correct but it should be a problem with core 2.4, however**_

![image](https://user-images.githubusercontent.com/5322669/57391426-86a79300-718c-11e9-9f0f-dddb6ff5bb17.png)


- when i installed mse 102 (testing branch) which should look specifically for "mil2525c" and "mil2525b" dictionaries the add-in was somehow adding the "mil2525c" and "mil2525bc2" dictionaries
![image](https://user-images.githubusercontent.com/5322669/57391381-6d9ee200-718c-11e9-9ea1-d11ee637bec5.png)
![image](https://user-images.githubusercontent.com/5322669/57391395-74c5f000-718c-11e9-9389-7609ed73ac65.png)

**Comment by dfoll** [comment]
after talking to @csmoore this was just "tester error" what i was looking at in the code `mil2525b` is just a variable name for the dictionary that is actually named "mil2525bc2", so everything is working as expected.

**Comment by dfoll** [comment]
Testing using Pro 2.4 (19590) and MSE 106 (which is the dev version built after merging #372 ).

Dictionary for 2525Bc2 or 2525C are  addeded 
![image](https://user-images.githubusercontent.com/5322669/57453701-0d17af80-7235-11e9-828e-677b3c0cc020.png)


![image](https://user-images.githubusercontent.com/5322669/57453678-fec99380-7234-11e9-963b-818d70089480.png)
