### ISSUE TITLE
Support APP6B in MSE

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-symbology#373]
Support APP6B

**Comment by csmoore** [comment]
Note: added a dependency on issue #362 / PR #366 - I can continue development with a local copy of the lpkx from this PR, but this PR would just need merged before this issue be tested.

**Comment by csmoore** [comment]
Adding this to the MSE seems to be working as expected ( [in branch](https://github.com/Esri/military-symbology/tree/csm-373-support-app6b-in-MSE) ) 

The only minor issue I am seeing (so far) is the issue we saw with some of the symbol names not being fully descriptive - https://github.com/Esri/military-symbology/issues/362#issuecomment-488819577 - and changed to the lpkx in https://github.com/Esri/military-symbology/commit/8d53937d157acc2f31e3d7ea2c836f092174a07c

Example:

![image](https://user-images.githubusercontent.com/3090809/57406917-f8450880-71af-11e9-9fe2-b88ee95fa418.png)

In the MSE, if you scroll down to the tags, you can get some more info on the symbol to be able to disambiguate so this issue may be more minor, and not sure if the stylx symbol names need to be updated

![image](https://user-images.githubusercontent.com/3090809/57407256-bec0cd00-71b0-11e9-8673-7246bbf25bc3.png)

**Comment by csmoore** [comment]
PR #375 submitted to add this support.

**Comment by dfoll** [comment]
- Looks like some echelons are missing:
- Platoon
- Company
- Regiment
- Corps 
![image](https://user-images.githubusercontent.com/5322669/57537261-eaa89380-7313-11e9-9b04-9f68db19738f.png)
- Is mobility supposed to show for units?  (seems like it does not in 2525D, but i did not check all the standards)
![image](https://user-images.githubusercontent.com/5322669/57537303-fdbb6380-7313-11e9-87d3-8e32f32bcc21.png)

**Comment by csmoore** [comment]
The missing echelons turns out to be a problem with our a couple domain values having special characters (tabs/spaces) - fixing these domain values will fix this:

![image](https://user-images.githubusercontent.com/3090809/57548399-d2923d80-732e-11e9-94e7-cf0bcb3c121e.png)

The missing mobility modifiers may be a problem we never caught with the updated arcade renderer, I am seeing this problem with 2525B/C also.

**Comment by lfunkhouser** [comment]
Update Echelon label to "Echelon/Mobility"

**Comment by csmoore** [comment]
Update PR #375 with most of the testing feedback.

New issues were created for the 2 issues that were not addressed:

1. Missing mobility modifiers -seems to be renderer issue: https://github.com/ArcGIS/military-symbology-styles/issues/193
2. Better restrict domain values for echelon/mobility - would be a larger fix and applies to other standards also: #377  

Sorry for the delay with this - I had a problem with packaging that only seems to show up on my machine (contacted Core)

**Comment by dfoll** [comment]
@csmoore I need some help on this one. When I get build 111 which is the most recent from [this branch](https://github.com/Esri/military-symbology/tree/csm-373-support-app6b-in-MSE) I am not seeing APP6B in the drop-down when trying to add a schema to the map

**Comment by csmoore** [comment]
@dfoll - it does require 2.4 to see the app6b option - unless it is a bug

**Comment by dfoll** [comment]
@csmoore my bad, was so sure that i had 2.4 on my system that I didn't even consider that as the problem.

**Comment by dfoll** [comment]
- APP-6(B) shows as an available schema (known to be only on 2.4)
- all echelons and mobility indicators show ( [comment here](https://github.com/Esri/military-symbology/issues/373#issuecomment-491325701) )

**Comment by dfoll** [comment]
TODO (doc work):
- [ ] update what's new page
   - [ ] update MT section
   - [ ] update MSE section
- [ ] update MT resources page
- [ ] update MSE resources page
- [ ] update MT home page
   - [ ] update overview
   - [ ] update what's new table

**Comment by dfoll** [comment]
TODO (doc verify):
- [ ] Defense [what's new page](https://solutionsdev.arcgis.com/defense/what-is-new/)
- [ ] [MT resources page](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm) 
- [ ] [MSE home page](https://solutionsdev.arcgis.com/defense/help/military-symbol-editor/)
- [ ] [MSE resources page](https://solutionsdev.arcgis.com/defense/help/military-symbol-editor/resources/june-2019-military-symbol-editor.htm)

**Comment by dfoll** [comment]
I have done the majority of this documentation. left the doc tags on awaiting response to email from @lfunkhouser @csmoore @kgonzago @ljuru after i get that response, we can fully remove all doc labels except for qc

**Comment by lfunkhouser** [comment]
Noticed there are no tests for the MSE that test APP-6. Added label to create tests.

**Comment by lfunkhouser** [comment]
doc reviewed. MSE verified on ...\MilitarySymbolEditor\Dev\119
MT verified on ...\MilitaryToolsForArcGIS\Dev\308
website doc updates verified on solutionsdev
Marking this issue as done. Issue to update tests is in the test repo, ...solutions-defense-test-catalog/issues/212
