### ISSUE TITLE
MSE Favorites not being saved at Pro 2.4

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbology#374]
A new problem has surfaced on Pro 2.4 where the favorites are no longer being preserved.

Repro steps:

0. On Pro 2.4
1. Launch Pro, Create Project, Launch MSE
2. Create some favorites
3. Close Pro
4. Launch Pro, reopen project
5. Click on Favorites Tab - Favorites are gone

The source of this problem seems to be changes that were made at Pro 2.4 with regards to the Assembly Cache (`C:\Users\{user}\AppData\Local\ESRI\ArcGISPro\AssemblyCache`):

1. The logic for determining if the assembly cache should be recreated from the .Addin file seems to have gotten much more aggressive (any change to the folder seems to trigger a rebuild from cache)
2. As a result, any files we add or change in the cache folder, seem to be causing the folder to get deleted and recreated when Pro launches
3. Because several of our addins (MSE, CC, DD) store configuration files (.config) to this cache folder location, these files will no longer be preserved.
4. Possible corrective actions:
    a. Contact Core and let them know about this issue: not to delete newer files or .config files
    b. Move config files to somewhere else (but these files are normally stored with the .dll or .exe so this might break the default .NET behavior)

**Comment by csmoore** [comment]
Sent email to Core asking if this - any file changes to the Addin cache folder cause the folder to be recreated - is expected behavior. We will likely have to move the config files to a different well-known folder for the 2.4 release (`Documents\ArcGIS`?).

**Comment by csmoore** [comment]
Added fix to PR #375 in commit https://github.com/Esri/military-symbology/pull/375/commits/84ed9a014bbe6154f5a26cf4e00dd53539cbc6da - ready for test

**Comment by dfoll** [comment]
Confirmed that on step 5 of the repro steps favorites exist if you open the previous project you were working in, or a new one. This was an internal change that I do not feel we need to document.
