### ISSUE TITLE
Holistic Testing: App Settings Browse button shift and dark-theme issue

### ISSUE THREAD

**Issue by mfunk** [Esri/military-symbology#387]
Found at Holistic Testing 8/9/2019:

onenote:///\\tahoe\holistic\ArcGISProfessional\Srinivas\Pro_v2_5\ProInternalHolistic_v2_5\August2019\Friday_08_09_2019.one#Pro%20for%20Intel&section-id={F5163543-00ED-4E04-962A-EF349811C6D0}&page-id={495373F4-9079-4A22-A025-E02A20F312F4}&end

Row 16, Tester Max:

![image](https://user-images.githubusercontent.com/3093182/62879471-0ab76c80-bce0-11e9-812a-a4d6b27e07a8.png)

![image](https://user-images.githubusercontent.com/3093182/62879480-0f7c2080-bce0-11e9-91ce-d524d3920516.png)

**Comment by csmoore** [comment]
This is a standard Pro dark theme button - and what they currently use for a disabled button. In this case the button is disabled because we don't currently support changing the schema database.
